pub(crate) mod standalone;
pub(crate) mod test_accessibility_coverage;
pub(crate) mod test_anchorgen_matrix;
pub(crate) mod test_behavior_matrix;
pub(crate) mod test_color_contrast_matrix;
pub(crate) mod test_coverage_gaps;
pub(crate) mod test_cross_origin_isolation;
pub(crate) mod test_deep_security_coverage;
mod test_focus_matrix;
pub(crate) mod test_generation_dedup;
mod test_hhier_matrix;
pub(crate) mod test_hsts_preload;
mod test_imgalt_matrix;
pub(crate) mod test_main;
pub(crate) mod test_panic_isolation;
pub(crate) mod test_permission_policy;
pub(crate) mod test_registry_uniqueness;
mod test_robots_blanket;
pub(crate) mod test_sri;
pub(crate) mod test_validator_coverage;
