#![allow(clippy::default_constructed_unit_structs)]
// Re-export all schema validators

mod action_schema;
mod action_schema_v2;
mod aggregate_offer_schema;
mod apartment_schema;
mod apartment_schema_v2;
mod article_schema;
mod book_schema_v2;
mod brand_schema;
mod breadcrumbs;
mod broadcast_event_schema;
mod car_schema;
mod car_schema_v2;
mod civic_structure_schema;
mod coupon_schema;
mod course_provider;
mod course_schema;
mod creative_work_schema;
mod dataset_schema;
mod educational_organization_schema;
mod event_location;
mod event_schema;
mod event_start_date;
mod faq_page_entity;
mod faq_schema;
mod food_establishment_schema;
mod government_service_schema;
mod government_service_schema_v2;
mod health_plan_schema;
mod health_plan_schema_v2;
mod how_to_schema;
mod howto_step_count;
mod invoice_schema;
mod invoice_schema_v2;
mod item_list_schema;
mod job_posting_salary;
mod job_posting_schema;
mod landform_schema;
mod landmarks_or_historical_buildings_schema;
mod local_business_hours;
mod local_business_nap;
mod local_business_npi;
mod local_business_schema;
mod lodging_business_schema;
mod movie_schema;
mod movie_schema_v2;
mod music_album_schema;
mod music_album_schema_v2;
mod music_recording_schema;
mod ngo_schema;
mod occupation_schema;
mod occupation_schema_v2;
mod offer_availability;
mod offer_schema;
mod organization_logo;
mod organization_sameas;
mod organization_schema;
mod performing_arts_series_schema;
mod permit_schema;
mod permit_schema_v2;
mod person_job_title;
mod person_schema;
mod plan_schema;
mod plan_schema_v2;
mod playbook_schema;
mod playbook_schema_v2;
mod playlist_schema;
mod product_availability;
mod product_model_schema;
mod product_model_schema_v2;
mod product_review;
mod quest_schema;
mod recipe_nutrition;
mod recipe_schema;
mod research_project_schema;
mod research_project_schema_v2;
mod review_schema;
mod schedule_schema;
mod schedule_schema_v2;
mod service_schema;
mod service_schema_v2;
mod shipping_schema;
mod software_application;
mod speakable_schema;
mod special_announcement_schema;
mod sports_activity_location_schema;
mod sports_event_schema;
mod tourist_attraction_schema;
mod tourist_destination_schema;
mod trip_schema;
mod trip_schema_v2;
mod tv_series_episode_schema;
mod tv_series_schema;
mod tv_series_schema_v2;
mod video_object_duration;
mod video_schema;
mod wearable_schema;
mod wearable_schema_v2;
mod web_api_schema;
mod web_api_schema_v2;
mod web_page_element_schema;
mod web_page_element_schema_v2;
mod web_page_schema;
mod web_site_schema;
mod web_site_schema_v2;
mod worker_schema;
mod worker_schema_v2;
mod workers_union_schema;
mod workers_union_schema_v2;

pub use action_schema::*;
pub use action_schema_v2::*;
pub use aggregate_offer_schema::*;
pub use apartment_schema::*;
pub use apartment_schema_v2::*;
pub use article_schema::*;
pub use book_schema_v2::*;
pub use brand_schema::*;
pub use breadcrumbs::*;
pub use broadcast_event_schema::*;
pub use car_schema::*;
pub use car_schema_v2::*;
pub use civic_structure_schema::*;
pub use coupon_schema::*;
pub use course_provider::*;
pub use course_schema::*;
pub use creative_work_schema::*;
pub use dataset_schema::*;
pub use educational_organization_schema::*;
pub use event_location::*;
pub use event_schema::*;
pub use event_start_date::*;
pub use faq_page_entity::*;
pub use faq_schema::*;
pub use food_establishment_schema::*;
pub use government_service_schema::*;
pub use government_service_schema_v2::*;
pub use health_plan_schema::*;
pub use health_plan_schema_v2::*;
pub use how_to_schema::*;
pub use howto_step_count::*;
pub use invoice_schema::*;
pub use invoice_schema_v2::*;
pub use item_list_schema::*;
pub use job_posting_salary::*;
pub use job_posting_schema::*;
pub use landform_schema::*;
pub use landmarks_or_historical_buildings_schema::*;
pub use local_business_hours::*;
pub use local_business_nap::*;
pub use local_business_npi::*;
pub use local_business_schema::*;
pub use lodging_business_schema::*;
pub use movie_schema::*;
pub use movie_schema_v2::*;
pub use music_album_schema::*;
pub use music_album_schema_v2::*;
pub use music_recording_schema::*;
pub use ngo_schema::*;
pub use occupation_schema::*;
pub use occupation_schema_v2::*;
pub use offer_availability::*;
pub use offer_schema::*;
pub use organization_logo::*;
pub use organization_sameas::*;
pub use organization_schema::*;
pub use performing_arts_series_schema::*;
pub use permit_schema::*;
pub use permit_schema_v2::*;
pub use person_job_title::*;
pub use person_schema::*;
pub use plan_schema::*;
pub use plan_schema_v2::*;
pub use playbook_schema::*;
pub use playbook_schema_v2::*;
pub use playlist_schema::*;
pub use product_availability::*;
pub use product_model_schema::*;
pub use product_model_schema_v2::*;
pub use product_review::*;
pub use quest_schema::*;
pub use recipe_nutrition::*;
pub use recipe_schema::*;
pub use research_project_schema::*;
pub use research_project_schema_v2::*;
pub use review_schema::*;
pub use schedule_schema::*;
pub use schedule_schema_v2::*;
pub use service_schema::*;
pub use service_schema_v2::*;
pub use shipping_schema::*;
pub use software_application::*;
pub use speakable_schema::*;
pub use special_announcement_schema::*;
pub use sports_activity_location_schema::*;
pub use sports_event_schema::*;
pub use tourist_attraction_schema::*;
pub use tourist_destination_schema::*;
pub use trip_schema::*;
pub use trip_schema_v2::*;
pub use tv_series_episode_schema::*;
pub use tv_series_schema::*;
pub use tv_series_schema_v2::*;
pub use video_object_duration::*;
pub use video_schema::*;
pub use wearable_schema::*;
pub use wearable_schema_v2::*;
pub use web_api_schema::*;
pub use web_api_schema_v2::*;
pub use web_page_element_schema::*;
pub use web_page_element_schema_v2::*;
pub use web_page_schema::*;
pub use web_site_schema::*;
pub use web_site_schema_v2::*;
pub use worker_schema::*;
pub use worker_schema_v2::*;
pub use workers_union_schema::*;
pub use workers_union_schema_v2::*;
