#![allow(clippy::default_constructed_unit_structs)]
// Re-export all schema validators

mod action_schema;
mod aggregate_offer_schema;
mod apartment_schema;
mod article_schema;
mod brand_schema;
mod breadcrumbs;
mod car_schema;
mod coupon_schema;
mod course_provider;
mod course_schema;
mod dataset_schema;
mod event_location;
mod event_schema;
mod faq_schema;
mod government_service_schema;
mod health_plan_schema;
mod how_to_schema;
mod invoice_schema;
mod item_list_schema;
mod job_posting_salary;
mod job_posting_schema;
mod local_business_hours;
mod local_business_nap;
mod local_business_schema;
mod movie_schema;
mod music_album_schema;
mod occupation_schema;
mod offer_availability;
mod offer_schema;
mod organization_logo;
mod organization_schema;
mod permit_schema;
mod person_job_title;
mod person_schema;
mod plan_schema;
mod playbook_schema;
mod product_model_schema;
mod product_review;
mod quest_schema;
mod recipe_nutrition;
mod recipe_schema;
mod research_project_schema;
mod review_schema;
mod schedule_schema;
mod service_schema;
mod shipping_schema;
mod software_application;
mod speakable_schema;
mod special_announcement_schema;
mod trip_schema;
mod tv_series_schema;
mod event_start_date;
mod faq_page_entity;
mod howto_step_count;
mod local_business_npi;
mod organization_sameas;
mod product_availability;
mod video_object_duration;
mod video_schema;
mod wearable_schema;
mod web_api_schema;
mod web_page_element_schema;
mod web_page_schema;
mod web_site_schema;
mod worker_schema;
mod workers_union_schema;

pub use action_schema::*;
pub use aggregate_offer_schema::*;
pub use apartment_schema::*;
pub use article_schema::*;
pub use brand_schema::*;
pub use breadcrumbs::*;
pub use car_schema::*;
pub use coupon_schema::*;
pub use course_provider::*;
pub use course_schema::*;
pub use dataset_schema::*;
pub use event_location::*;
pub use event_schema::*;
pub use faq_schema::*;
pub use government_service_schema::*;
pub use health_plan_schema::*;
pub use how_to_schema::*;
pub use invoice_schema::*;
pub use item_list_schema::*;
pub use job_posting_salary::*;
pub use job_posting_schema::*;
pub use local_business_hours::*;
pub use local_business_nap::*;
pub use local_business_schema::*;
pub use movie_schema::*;
pub use music_album_schema::*;
pub use occupation_schema::*;
pub use offer_availability::*;
pub use offer_schema::*;
pub use organization_logo::*;
pub use organization_schema::*;
pub use permit_schema::*;
pub use person_job_title::*;
pub use person_schema::*;
pub use plan_schema::*;
pub use playbook_schema::*;
pub use product_model_schema::*;
pub use product_review::*;
pub use quest_schema::*;
pub use recipe_nutrition::*;
pub use recipe_schema::*;
pub use research_project_schema::*;
pub use review_schema::*;
pub use schedule_schema::*;
pub use service_schema::*;
pub use shipping_schema::*;
pub use software_application::*;
pub use speakable_schema::*;
pub use special_announcement_schema::*;
pub use trip_schema::*;
pub use tv_series_schema::*;
pub use event_start_date::*;
pub use faq_page_entity::*;
pub use howto_step_count::*;
pub use local_business_npi::*;
pub use organization_sameas::*;
pub use product_availability::*;
pub use video_object_duration::*;
pub use video_schema::*;
pub use wearable_schema::*;
pub use web_api_schema::*;
pub use web_page_element_schema::*;
pub use web_page_schema::*;
pub use web_site_schema::*;
pub use worker_schema::*;
pub use workers_union_schema::*;
