use chrono::{DateTime, Utc};
use lru::LruCache;
use parking_lot::Mutex;
use rusqlite::{params, Connection, Row};
use std::num::NonZeroUsize;
use std::path::Path;
use std::sync::atomic::{AtomicUsize, Ordering};
use thiserror::Error;
use url::Url;

/// Errors specific to storage operations.
///
/// Wraps SQLite database errors and URL parsing errors that can occur
/// during crawl data persistence.
#[derive(Debug, Error)]
pub enum StorageError {
    /// SQLite database error.
    #[error("database error: {0}")]
    Database(#[from] rusqlite::Error),

    /// URL parsing error during retrieval.
    #[error("invalid URL in database: {0}")]
    InvalidUrl(#[from] url::ParseError),

    /// The operation is not supported by this storage backend.
    #[error("operation not supported by this backend: {0}")]
    Unsupported(String),

    /// A stored timestamp could not be parsed.
    #[error("invalid timestamp in database: {0}")]
    InvalidTimestamp(String),

    /// PostgreSQL database error.
    #[cfg(feature = "postgres")]
    #[error("postgresql error: {0}")]
    PgDatabase(#[from] sqlx::Error),

    /// PostgreSQL migration error.
    #[cfg(feature = "postgres")]
    #[error("migration error: {0}")]
    PgMigration(String),
}

// `From<StorageError> for CrawlError` is generated by the `#[from]`
// attribute on `CrawlError::Storage` in `lib.rs`.

// Severity and IssueCategory are defined in `types` so they are available
// without the `full` feature gate. Re-export for backward compatibility.
pub use crate::types::{IssueCategory, Severity};

/// A page extracted from the crawl, with full data for storage.
///
/// Contains all metadata needed to persist a crawled page to the database,
/// including URL, status, content metrics, and discovered links.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PageData {
    /// Unique page identifier.
    pub id: String,
    /// The URL of the page.
    pub url: Url,
    /// The final URL after redirects.
    pub final_url: Url,
    /// The HTTP status code.
    pub status_code: u16,
    /// The page title.
    pub title: Option<String>,
    /// The meta description.
    pub description: Option<String>,
    /// The canonical URL.
    pub canonical_url: Option<Url>,
    /// Word count of the page body.
    pub word_count: Option<usize>,
    /// Response time in milliseconds.
    pub load_time_ms: Option<u64>,
    /// Body size in bytes.
    pub body_size: Option<usize>,
    /// When this page was fetched.
    pub fetched_at: DateTime<Utc>,
    /// Links discovered on this page.
    pub links: Vec<Url>,
    /// Tenant ID for multi-tenancy.
    pub tenant_id: Option<String>,
    /// ETag header value from the last fetch.
    pub etag: Option<String>,
    /// Last-Modified header value from the last fetch.
    pub last_modified: Option<String>,
    /// Largest Contentful Paint in milliseconds (lab measurement).
    pub cwv_lcp: Option<f64>,
    /// Cumulative Layout Shift (dimensionless, lab measurement).
    pub cwv_cls: Option<f64>,
    /// Interaction to Next Paint in milliseconds (lab measurement).
    pub cwv_inp: Option<f64>,
    /// Whether the page has any structured data (JSON-LD, microdata, RDFa).
    pub has_structured_data: Option<bool>,
    /// Comma-separated list of schema types present on the page.
    pub schema_types: Option<String>,
    /// Whether the viewport meta tag is properly configured.
    pub viewport_ok: Option<bool>,
    /// Whether the page has a Content-Security-Policy header.
    pub has_csp: Option<bool>,
    /// Whether the page has a Strict-Transport-Security header.
    pub has_hsts: Option<bool>,
    /// Total number of images on the page.
    pub images_total: Option<usize>,
    /// Number of images missing alt text.
    pub images_missing_alt: Option<usize>,
    /// Number of H1 headings on the page.
    pub h1_count: Option<usize>,
    /// Total number of headings (H1-H6) on the page.
    pub heading_count: Option<usize>,
    /// JSON-serialized custom extraction results: `Vec<(String, Vec<String>)>`.
    /// Each tuple is `(rule_name, extracted_values)`. `None` when no extraction
    /// rules are configured for the crawl.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extractions: Option<String>,
}

#[allow(clippy::unwrap_used)]
impl Default for PageData {
    fn default() -> Self {
        Self {
            id: String::new(),
            url: Url::parse("https://example.com").unwrap(),
            final_url: Url::parse("https://example.com").unwrap(),
            status_code: 200,
            title: None,
            description: None,
            canonical_url: None,
            word_count: None,
            load_time_ms: None,
            body_size: None,
            fetched_at: chrono::Utc::now(),
            links: Vec::new(),
            tenant_id: None,
            etag: None,
            last_modified: None,
            cwv_lcp: None,
            cwv_cls: None,
            cwv_inp: None,
            has_structured_data: None,
            schema_types: None,
            viewport_ok: None,
            has_csp: None,
            has_hsts: None,
            images_total: None,
            images_missing_alt: None,
            h1_count: None,
            heading_count: None,
            extractions: None,
        }
    }
}

/// An issue/finding detected during analysis.
///
/// Persisted to the database with a reference to the page it belongs to.
/// Includes category, severity, machine-readable code, and recommendation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Issue {
    /// Unique issue identifier.
    pub id: String,
    /// The page this issue belongs to.
    pub page_id: String,
    /// Issue category.
    pub category: IssueCategory,
    /// Issue severity.
    pub severity: Severity,
    /// Machine-readable issue code (e.g. "SEO001").
    pub code: String,
    /// Human-readable title.
    pub title: String,
    /// Detailed description.
    pub description: String,
    /// CSS selector of the affected element, if applicable.
    pub element: Option<String>,
    /// Recommendation for fixing the issue.
    pub recommendation: String,
    /// Tenant ID for multi-tenancy.
    pub tenant_id: Option<String>,
}

/// Filters for querying issues.
///
/// All fields are optional. When set, they narrow the query results.
/// When `None`, that filter dimension is not applied.
#[derive(Debug, Clone, Default)]
pub struct IssueFilter {
    /// Filter by severity.
    pub severity: Option<Severity>,
    /// Filter by category.
    pub category: Option<IssueCategory>,
    /// Filter by page ID.
    pub page_id: Option<String>,
    /// Filter by issue code prefix.
    pub code_prefix: Option<String>,
}

/// Aggregate crawl statistics.
///
/// Summary of pages crawled, issues found, and performance metrics.
/// Returned by [`Storage::get_stats`].
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct CrawlStats {
    /// Total number of pages crawled.
    pub total_pages: usize,
    /// Total number of issues found.
    pub total_issues: usize,
    /// Issues by severity.
    pub issues_by_severity: std::collections::HashMap<String, usize>,
    /// Issues by category.
    pub issues_by_category: std::collections::HashMap<String, usize>,
    /// Average response time in milliseconds.
    pub avg_response_time_ms: Option<f64>,
    /// Total body size in bytes.
    pub total_body_size: Option<usize>,
}

/// Cache statistics for the LRU page cache.
#[derive(Debug, Clone)]
pub struct CacheStats {
    /// Maximum cache capacity.
    pub capacity: usize,
    /// Current number of cached entries.
    pub size: usize,
    /// Cache hit count (since last reset).
    pub hits: usize,
    /// Cache miss count (since last reset).
    pub misses: usize,
}

/// SQLite-backed storage for crawl data.
///
/// Uses WAL mode for concurrent-safe access and provides
/// batch-friendly insert methods for performance. Includes an LRU cache
/// for frequently accessed pages and memory usage tracking.
pub struct Storage {
    conn: Mutex<Connection>,
    /// LRU cache for recently accessed pages.
    page_cache: Mutex<LruCache<String, PageData>>,
    /// Approximate memory usage in bytes.
    memory_usage: AtomicUsize,
    /// Whether memory-mapped I/O is enabled (for read-heavy workloads).
    mmap_enabled: bool,
}

impl Storage {
    /// Lock and return the underlying connection guard.
    ///
    /// Provides direct access to the SQLite connection for advanced
    /// queries or transactions not covered by the convenience methods.
    pub fn conn(&self) -> parking_lot::MutexGuard<'_, Connection> {
        self.conn.lock()
    }

    /// Open or create a SQLite database at the given path.
    ///
    /// Enables WAL mode, memory-mapped I/O, and creates the schema if it
    /// doesn't exist. Uses a default LRU cache of 1000 entries.
    ///
    /// # Errors
    ///
    /// Returns [`StorageError::Database`] if the database cannot be opened
    /// or the schema cannot be created.
    pub fn new(path: &Path) -> Result<Self, StorageError> {
        let conn = Connection::open(path)?;

        // Enable WAL mode for concurrent-safe reads/writes
        // Enable memory-mapped I/O for faster reads (256MB)
        conn.execute_batch(
            "PRAGMA journal_mode=WAL;
             PRAGMA foreign_keys=ON;
             PRAGMA mmap_size=268435456;
             PRAGMA cache_size=-64000;
             PRAGMA synchronous=NORMAL;",
        )?;

        let storage = Self {
            conn: Mutex::new(conn),
            page_cache: Mutex::new(LruCache::new(
                NonZeroUsize::new(1000).unwrap_or(NonZeroUsize::MIN),
            )),
            memory_usage: AtomicUsize::new(0),
            mmap_enabled: true,
        };
        storage.create_schema()?;
        Ok(storage)
    }

    /// Create in-memory storage for testing.
    ///
    /// Uses an in-memory SQLite database with WAL mode enabled.
    /// Ideal for unit tests that need fast, isolated storage.
    ///
    /// # Errors
    ///
    /// Returns [`StorageError::Database`] if the in-memory database
    /// cannot be created.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use crawlkit_engine::storage::Storage;
    ///
    /// let storage = Storage::new_in_memory().unwrap();
    /// let crawl_id = storage.start_crawl("https://example.com", None).unwrap();
    /// assert!(!crawl_id.is_empty());
    /// ```
    pub fn new_in_memory() -> Result<Self, StorageError> {
        let conn = Connection::open_in_memory()?;
        conn.execute_batch(
            "PRAGMA journal_mode=WAL;
             PRAGMA foreign_keys=ON;
             PRAGMA cache_size=-64000;",
        )?;
        let storage = Self {
            conn: Mutex::new(conn),
            page_cache: Mutex::new(LruCache::new(
                NonZeroUsize::new(1000).unwrap_or(NonZeroUsize::MIN),
            )),
            memory_usage: AtomicUsize::new(0),
            mmap_enabled: false,
        };
        storage.create_schema()?;
        Ok(storage)
    }

    /// Create storage with a custom LRU cache size.
    ///
    /// Use this when the default 1000-entry cache is not appropriate
    /// for your workload. Larger caches improve read performance for
    /// repeat queries but use more memory.
    ///
    /// # Errors
    ///
    /// Returns [`StorageError::Database`] if the database cannot be opened.
    pub fn with_cache_size(path: &Path, cache_size: usize) -> Result<Self, StorageError> {
        let conn = Connection::open(path)?;

        conn.execute_batch(
            "PRAGMA journal_mode=WAL;
             PRAGMA foreign_keys=ON;
             PRAGMA mmap_size=268435456;
             PRAGMA cache_size=-64000;
             PRAGMA synchronous=NORMAL;",
        )?;

        let storage = Self {
            conn: Mutex::new(conn),
            page_cache: Mutex::new(LruCache::new(
                NonZeroUsize::new(cache_size).unwrap_or(NonZeroUsize::MIN),
            )),
            memory_usage: AtomicUsize::new(0),
            mmap_enabled: true,
        };
        storage.create_schema()?;
        Ok(storage)
    }

    /// Returns the approximate memory usage in bytes.
    pub fn memory_usage(&self) -> usize {
        self.memory_usage.load(Ordering::Relaxed)
    }

    /// Returns whether memory-mapped I/O is enabled.
    pub fn is_mmap_enabled(&self) -> bool {
        self.mmap_enabled
    }

    /// Returns cache statistics (hits, misses, current size).
    pub fn cache_stats(&self) -> CacheStats {
        let cache = self.page_cache.lock();
        CacheStats {
            capacity: cache.cap().get(),
            size: cache.len(),
            hits: 0, // Would need to track these separately
            misses: 0,
        }
    }

    /// Clears the page cache.
    pub fn clear_cache(&self) {
        let mut cache = self.page_cache.lock();
        cache.clear();
        self.memory_usage.store(0, Ordering::Relaxed);
    }

    /// Create the database schema if it doesn't already exist.
    fn create_schema(&self) -> Result<(), StorageError> {
        let conn = self.conn.lock();

        conn.execute_batch(
            "
            CREATE TABLE IF NOT EXISTS crawls (
                id            TEXT PRIMARY KEY,
                start_time    DATETIME NOT NULL,
                end_time      DATETIME,
                target_url    TEXT NOT NULL,
                pages_crawled INTEGER DEFAULT 0,
                total_issues  INTEGER DEFAULT 0,
                config_json   TEXT
            );

            CREATE TABLE IF NOT EXISTS pages (
                id            TEXT PRIMARY KEY,
                crawl_id      TEXT NOT NULL REFERENCES crawls(id),
                url           TEXT NOT NULL,
                final_url     TEXT NOT NULL,
                status_code   INTEGER NOT NULL,
                title         TEXT,
                description   TEXT,
                canonical     TEXT,
                word_count    INTEGER,
                load_time_ms  INTEGER,
                body_size     INTEGER,
                fetched_at    DATETIME NOT NULL,
                tenant_id     TEXT,
                etag          TEXT,
                last_modified TEXT,
                cwv_lcp       REAL,
                cwv_cls       REAL,
                cwv_inp       REAL,
                UNIQUE(crawl_id, url)
            );

            CREATE TABLE IF NOT EXISTS links (
                id            TEXT PRIMARY KEY,
                page_id       TEXT NOT NULL REFERENCES pages(id),
                source_url    TEXT NOT NULL,
                target_url    TEXT NOT NULL,
                anchor_text   TEXT,
                rel           TEXT,
                is_external   BOOLEAN,
                is_nofollow   BOOLEAN
            );

            CREATE TABLE IF NOT EXISTS findings (
                id            TEXT PRIMARY KEY,
                page_id       TEXT NOT NULL REFERENCES pages(id),
                category      TEXT NOT NULL,
                severity      TEXT NOT NULL,
                code          TEXT NOT NULL,
                title         TEXT NOT NULL,
                description   TEXT NOT NULL,
                element       TEXT,
                recommendation TEXT,
                tenant_id     TEXT
            );

            CREATE TABLE IF NOT EXISTS images (
                id            TEXT PRIMARY KEY,
                page_id       TEXT NOT NULL REFERENCES pages(id),
                url           TEXT NOT NULL,
                alt           TEXT,
                width         INTEGER,
                height        INTEGER,
                format        TEXT,
                file_size     INTEGER,
                is_lazy_loaded BOOLEAN
            );

            CREATE TABLE IF NOT EXISTS schemas (
                id            TEXT PRIMARY KEY,
                page_id       TEXT NOT NULL REFERENCES pages(id),
                schema_type   TEXT NOT NULL,
                data_json     TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS crux_metrics (
                id            TEXT PRIMARY KEY,
                page_id       TEXT NOT NULL REFERENCES pages(id),
                url           TEXT NOT NULL,
                lcp_p75       REAL,
                inp_p75       REAL,
                cls_p75       REAL,
                fcp_p75       REAL,
                ttfb_p75      REAL,
                fetched_at    DATETIME NOT NULL,
                UNIQUE(page_id)
            );

            CREATE TABLE IF NOT EXISTS rank_projects (
                id            TEXT PRIMARY KEY,
                domain        TEXT NOT NULL,
                search_engine TEXT NOT NULL DEFAULT 'duckduckgo',
                device        TEXT NOT NULL DEFAULT 'desktop',
                locale        TEXT NOT NULL DEFAULT 'en-US',
                created_at    DATETIME NOT NULL
            );

            CREATE TABLE IF NOT EXISTS rank_keywords (
                id              TEXT PRIMARY KEY,
                project_id      TEXT NOT NULL REFERENCES rank_projects(id),
                keyword         TEXT NOT NULL,
                target_url      TEXT,
                enabled         BOOLEAN NOT NULL DEFAULT 1,
                last_checked_at DATETIME,
                created_at      DATETIME NOT NULL,
                UNIQUE(project_id, keyword)
            );

            CREATE TABLE IF NOT EXISTS rank_positions (
                id         TEXT PRIMARY KEY,
                keyword_id TEXT NOT NULL REFERENCES rank_keywords(id),
                checked_at DATETIME NOT NULL,
                position   INTEGER,
                url        TEXT,
                title      TEXT,
                source     TEXT NOT NULL,
                UNIQUE(keyword_id, checked_at, source)
            );

            CREATE TABLE IF NOT EXISTS query_positions (
                query      TEXT NOT NULL,
                date       TEXT NOT NULL,
                source     TEXT NOT NULL,
                clicks     INTEGER NOT NULL DEFAULT 0,
                impressions INTEGER NOT NULL DEFAULT 0,
                position   REAL NOT NULL DEFAULT 0,
                ctr        REAL NOT NULL DEFAULT 0,
                PRIMARY KEY (query, date, source)
            );

            CREATE INDEX IF NOT EXISTS idx_pages_crawl ON pages(crawl_id);
            CREATE INDEX IF NOT EXISTS idx_pages_tenant ON pages(tenant_id);
            CREATE INDEX IF NOT EXISTS idx_links_source ON links(source_url);
            CREATE INDEX IF NOT EXISTS idx_links_target ON links(target_url);
            CREATE INDEX IF NOT EXISTS idx_findings_page ON findings(page_id);
            CREATE INDEX IF NOT EXISTS idx_findings_category ON findings(category);
            CREATE INDEX IF NOT EXISTS idx_findings_severity ON findings(severity);
            CREATE INDEX IF NOT EXISTS idx_findings_tenant ON findings(tenant_id);
            CREATE INDEX IF NOT EXISTS idx_rank_keywords_project ON rank_keywords(project_id);
            CREATE INDEX IF NOT EXISTS idx_rank_positions_keyword ON rank_positions(keyword_id, checked_at);
            ",
        )?;

        // Migrate: add new columns if they don't exist yet.
        let columns: Vec<String> = conn
            .prepare("PRAGMA table_info(pages)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .collect::<Result<Vec<_>, _>>()?;

        // Column types must match how the values are bound (integers for
        // booleans/counts) and read (`Option<i64>` in `row_to_page_data`).
        // TEXT affinity would coerce stored integers to strings and break
        // integer reads with `InvalidColumnType`.
        let new_columns: [(&str, &str); 10] = [
            ("has_structured_data", "INTEGER"),
            ("schema_types", "TEXT"),
            ("viewport_ok", "INTEGER"),
            ("has_csp", "INTEGER"),
            ("has_hsts", "INTEGER"),
            ("images_total", "INTEGER"),
            ("images_missing_alt", "INTEGER"),
            ("h1_count", "INTEGER"),
            ("heading_count", "INTEGER"),
            ("extractions", "TEXT"),
        ];
        for (col, col_type) in new_columns {
            if !columns.contains(&col.to_string()) {
                conn.execute(
                    &format!("ALTER TABLE pages ADD COLUMN {col} {col_type}"),
                    [],
                )?;
            }
        }

        Ok(())
    }

    /// Start a new crawl and return its ID.
    pub fn start_crawl(
        &self,
        target_url: &str,
        config_json: Option<&str>,
    ) -> Result<String, StorageError> {
        let crawl_id = uuid::Uuid::new_v4().to_string();
        let conn = self.conn.lock();
        conn.execute(
            "INSERT INTO crawls (id, start_time, target_url, config_json) VALUES (?1, ?2, ?3, ?4)",
            params![crawl_id, Utc::now().to_rfc3339(), target_url, config_json,],
        )?;
        Ok(crawl_id)
    }

    /// Finish a crawl, recording final statistics.
    pub fn finish_crawl(
        &self,
        crawl_id: &str,
        pages_crawled: usize,
        total_issues: usize,
    ) -> Result<(), StorageError> {
        let conn = self.conn.lock();
        conn.execute(
            "UPDATE crawls SET end_time = ?1, pages_crawled = ?2, total_issues = ?3 WHERE id = ?4",
            params![
                Utc::now().to_rfc3339(),
                pages_crawled,
                total_issues,
                crawl_id
            ],
        )?;
        Ok(())
    }

    /// Purge crawls older than `max_age_days` days.
    ///
    /// Cascades to pages, findings, links, images, schemas, and CrUX
    /// metrics via foreign keys. Returns the number of crawls deleted.
    pub fn purge_old_crawls(&self, max_age_days: u32) -> Result<usize, StorageError> {
        let conn = self.conn.lock();
        let cutoff = Utc::now() - chrono::Duration::days(i64::from(max_age_days));
        let cutoff_rfc = cutoff.to_rfc3339();

        // Collect IDs to delete (foreign keys handle cascading).
        let crawl_ids: Vec<String> = {
            let mut stmt = conn.prepare("SELECT id FROM crawls WHERE start_time < ?1")?;
            let ids = stmt
                .query_map(params![cutoff_rfc], |row| row.get::<_, String>(0))?
                .collect::<Result<Vec<_>, _>>()?;
            ids
        };

        let count = crawl_ids.len();
        if count == 0 {
            return Ok(0);
        }

        // Delete in a transaction for atomicity.
        let tx = conn.unchecked_transaction()?;
        for crawl_id in &crawl_ids {
            // Children are deleted via ON DELETE CASCADE (foreign keys are
            // enabled). We issue explicit deletes for tables that reference
            // `crawls(id)` directly to guarantee cleanup even if a child
            // table lacks a cascade.
            tx.execute(
                "DELETE FROM links WHERE page_id IN (SELECT id FROM pages WHERE crawl_id = ?1)",
                params![crawl_id],
            )?;
            tx.execute(
                "DELETE FROM findings WHERE page_id IN (SELECT id FROM pages WHERE crawl_id = ?1)",
                params![crawl_id],
            )?;
            tx.execute(
                "DELETE FROM images WHERE page_id IN (SELECT id FROM pages WHERE crawl_id = ?1)",
                params![crawl_id],
            )?;
            tx.execute(
                "DELETE FROM schemas WHERE page_id IN (SELECT id FROM pages WHERE crawl_id = ?1)",
                params![crawl_id],
            )?;
            tx.execute("DELETE FROM crux_metrics WHERE page_id IN (SELECT id FROM pages WHERE crawl_id = ?1)", params![crawl_id])?;
            tx.execute("DELETE FROM pages WHERE crawl_id = ?1", params![crawl_id])?;
            tx.execute("DELETE FROM crawls WHERE id = ?1", params![crawl_id])?;
        }
        tx.commit()?;

        tracing::info!("Purged {count} crawls older than {max_age_days} days");
        Ok(count)
    }

    /// Purge crawls older than `max_age_days` days for a specific tenant.
    ///
    /// Only deletes crawls that contain pages belonging to the given tenant.
    /// Cascades to pages, findings, links, images, schemas, and CrUX
    /// metrics via foreign keys. Returns the number of crawls deleted.
    pub fn purge_old_crawls_for_tenant(
        &self,
        max_age_days: u32,
        tenant_id: &str,
    ) -> Result<usize, StorageError> {
        let conn = self.conn.lock();
        let cutoff = Utc::now() - chrono::Duration::days(i64::from(max_age_days));
        let cutoff_rfc = cutoff.to_rfc3339();

        // Collect crawl IDs that have pages belonging to this tenant.
        let crawl_ids: Vec<String> = {
            let mut stmt = conn.prepare(
                "SELECT DISTINCT c.id FROM crawls c
                 JOIN pages p ON p.crawl_id = c.id
                 WHERE c.start_time < ?1 AND (p.tenant_id = ?2 OR p.tenant_id IS NULL)",
            )?;
            let ids = stmt
                .query_map(params![cutoff_rfc, tenant_id], |row| {
                    row.get::<_, String>(0)
                })?
                .collect::<Result<Vec<_>, _>>()?;
            ids
        };

        let count = crawl_ids.len();
        if count == 0 {
            return Ok(0);
        }

        // Delete in a transaction for atomicity.
        let tx = conn.unchecked_transaction()?;
        for crawl_id in &crawl_ids {
            tx.execute(
                "DELETE FROM links WHERE page_id IN (SELECT id FROM pages WHERE crawl_id = ?1)",
                params![crawl_id],
            )?;
            tx.execute(
                "DELETE FROM findings WHERE page_id IN (SELECT id FROM pages WHERE crawl_id = ?1)",
                params![crawl_id],
            )?;
            tx.execute(
                "DELETE FROM images WHERE page_id IN (SELECT id FROM pages WHERE crawl_id = ?1)",
                params![crawl_id],
            )?;
            tx.execute(
                "DELETE FROM schemas WHERE page_id IN (SELECT id FROM pages WHERE crawl_id = ?1)",
                params![crawl_id],
            )?;
            tx.execute("DELETE FROM crux_metrics WHERE page_id IN (SELECT id FROM pages WHERE crawl_id = ?1)", params![crawl_id])?;
            tx.execute("DELETE FROM pages WHERE crawl_id = ?1", params![crawl_id])?;
            tx.execute("DELETE FROM crawls WHERE id = ?1", params![crawl_id])?;
        }
        tx.commit()?;

        tracing::info!(
            "Purged {count} crawls older than {max_age_days} days for tenant {tenant_id}"
        );
        Ok(count)
    }

    /// Composite LRU cache key: pages are unique per `(crawl_id, url)`,
    /// so caching by URL alone would leak pages across crawls (and thus
    /// across tenants in multi-tenant deployments).
    fn cache_key(crawl_id: &str, url: &str) -> String {
        // \u{1} is a control character that cannot appear unescaped in a
        // URL, making the (crawl_id, url) pair unambiguous.
        format!("{crawl_id}\u{1}{url}")
    }

    /// Insert a single page into the database under the given crawl.
    /// Uses a single SQLite transaction for the page row + all link rows
    /// to avoid per-statement fsync overhead.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use crawlkit_engine::storage::{Storage, PageData};
    /// use chrono::Utc;
    /// use url::Url;
    ///
    /// let storage = Storage::new_in_memory().unwrap();
    /// let crawl_id = storage.start_crawl("https://example.com", None).unwrap();
    ///
    /// let page = PageData {
    ///     id: "page-1".to_string(),
    ///     url: Url::parse("https://example.com/").unwrap(),
    ///     final_url: Url::parse("https://example.com/").unwrap(),
    ///     status_code: 200,
    ///     title: Some("Home".to_string()),
    ///     description: None,
    ///     canonical_url: None,
    ///     word_count: Some(500),
    ///     load_time_ms: Some(150),
    ///     body_size: Some(4096),
    ///     fetched_at: Utc::now(),
    ///     links: vec![],
    ///     tenant_id: None,
    ///     etag: None,
    ///     last_modified: None,
    ///     cwv_lcp: None,
    ///     cwv_cls: None,
    ///     cwv_inp: None,
    ///     has_structured_data: None,
    ///     schema_types: None,
    ///     viewport_ok: None,
    ///     has_csp: None,
    ///     has_hsts: None,
    ///     images_total: None,
    ///     images_missing_alt: None,
    ///     h1_count: None,
    ///     heading_count: None,
    ///     extractions: None,
    /// };
    ///
    /// storage.insert_page(&crawl_id, &page).unwrap();
    /// let pages = storage.get_pages(&crawl_id, 10).unwrap();
    /// assert_eq!(pages.len(), 1);
    /// ```
    pub fn insert_page(&self, crawl_id: &str, page: &PageData) -> Result<(), StorageError> {
        let conn = self.conn.lock();
        let tx = conn.unchecked_transaction()?;

        tx.execute(
            "INSERT OR REPLACE INTO pages (id, crawl_id, url, final_url, status_code, title, description, canonical, word_count, load_time_ms, body_size, fetched_at, tenant_id, etag, last_modified, cwv_lcp, cwv_cls, cwv_inp, has_structured_data, schema_types, viewport_ok, has_csp, has_hsts, images_total, images_missing_alt, h1_count, heading_count, extractions)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24, ?25, ?26, ?27, ?28)",
            params![
                page.id,
                crawl_id,
                page.url.as_str(),
                page.final_url.as_str(),
                page.status_code,
                page.title,
                page.description,
                page.canonical_url.as_ref().map(|u| u.as_str()),
                page.word_count.map(|v| v as i64),
                page.load_time_ms.map(|v| v as i64),
                page.body_size.map(|v| v as i64),
                page.fetched_at.to_rfc3339(),
                page.tenant_id,
                page.etag,
                page.last_modified,
                page.cwv_lcp,
                page.cwv_cls,
                page.cwv_inp,
                page.has_structured_data.map(|v| if v { 1 } else { 0 }),
                page.schema_types,
                page.viewport_ok.map(|v| if v { 1 } else { 0 }),
                page.has_csp.map(|v| if v { 1 } else { 0 }),
                page.has_hsts.map(|v| if v { 1 } else { 0 }),
                page.images_total.map(|v| v as i64),
                page.images_missing_alt.map(|v| v as i64),
                page.h1_count.map(|v| v as i64),
                page.heading_count.map(|v| v as i64),
                page.extractions,
            ],
        )?;

        // Insert links within the same transaction
        let mut stmt = tx.prepare(
            "INSERT INTO links (id, page_id, source_url, target_url, is_external) VALUES (?1, ?2, ?3, ?4, ?5)",
        )?;
        for link in &page.links {
            let link_id = uuid::Uuid::new_v4().to_string();
            let is_external = link.domain() != page.url.domain();
            stmt.execute(params![
                link_id,
                page.id,
                page.url.as_str(),
                link.as_str(),
                is_external,
            ])?;
        }
        drop(stmt);

        tx.commit()?;

        let mut cache = self.page_cache.lock();
        let page_size = std::mem::size_of::<PageData>()
            + page.url.as_str().len()
            + page.title.as_deref().unwrap_or("").len();
        cache.put(Self::cache_key(crawl_id, page.url.as_str()), page.clone());
        self.memory_usage.fetch_add(page_size, Ordering::Relaxed);

        Ok(())
    }

    /// Insert a batch of pages for performance.
    /// Wraps all inserts in a single SQLite transaction for O(n) vs O(n*fsync).
    pub fn insert_pages(&self, crawl_id: &str, pages: &[PageData]) -> Result<(), StorageError> {
        if pages.is_empty() {
            return Ok(());
        }
        let conn = self.conn.lock();
        let tx = conn.unchecked_transaction()?;

        let mut page_stmt = tx.prepare(
            "INSERT OR REPLACE INTO pages (id, crawl_id, url, final_url, status_code, title, description, canonical, word_count, load_time_ms, body_size, fetched_at, tenant_id, etag, last_modified, cwv_lcp, cwv_cls, cwv_inp, has_structured_data, schema_types, viewport_ok, has_csp, has_hsts, images_total, images_missing_alt, h1_count, heading_count, extractions)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24, ?25, ?26, ?27, ?28)",
        )?;
        let mut link_stmt = tx.prepare(
            "INSERT INTO links (id, page_id, source_url, target_url, is_external) VALUES (?1, ?2, ?3, ?4, ?5)",
        )?;

        for page in pages {
            page_stmt.execute(params![
                page.id,
                crawl_id,
                page.url.as_str(),
                page.final_url.as_str(),
                page.status_code,
                page.title,
                page.description,
                page.canonical_url.as_ref().map(|u| u.as_str()),
                page.word_count.map(|v| v as i64),
                page.load_time_ms.map(|v| v as i64),
                page.body_size.map(|v| v as i64),
                page.fetched_at.to_rfc3339(),
                page.tenant_id,
                page.etag,
                page.last_modified,
                page.cwv_lcp,
                page.cwv_cls,
                page.cwv_inp,
                page.has_structured_data.map(|v| if v { 1 } else { 0 }),
                page.schema_types,
                page.viewport_ok.map(|v| if v { 1 } else { 0 }),
                page.has_csp.map(|v| if v { 1 } else { 0 }),
                page.has_hsts.map(|v| if v { 1 } else { 0 }),
                page.images_total.map(|v| v as i64),
                page.images_missing_alt.map(|v| v as i64),
                page.h1_count.map(|v| v as i64),
                page.heading_count.map(|v| v as i64),
                page.extractions,
            ])?;

            for link in &page.links {
                let link_id = uuid::Uuid::new_v4().to_string();
                let is_external = link.domain() != page.url.domain();
                link_stmt.execute(params![
                    link_id,
                    page.id,
                    page.url.as_str(),
                    link.as_str(),
                    is_external,
                ])?;
            }
        }

        drop(link_stmt);
        drop(page_stmt);
        tx.commit()?;
        Ok(())
    }

    /// Insert a single issue/finding into the database.
    pub fn insert_issue(&self, issue: &Issue) -> Result<(), StorageError> {
        let conn = self.conn.lock();
        conn.execute(
            "INSERT INTO findings (id, page_id, category, severity, code, title, description, element, recommendation, tenant_id)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)",
            params![
                issue.id,
                issue.page_id,
                issue.category.as_str(),
                issue.severity.as_str(),
                issue.code,
                issue.title,
                issue.description,
                issue.element,
                issue.recommendation,
                issue.tenant_id,
            ],
        )?;
        Ok(())
    }

    /// Update the `fetched_at` timestamp of an existing page (304 Not Modified path).
    pub fn update_page_fetched_at(
        &self,
        page_id: &str,
        fetched_at: chrono::DateTime<chrono::Utc>,
    ) -> Result<(), StorageError> {
        let conn = self.conn.lock();
        conn.execute(
            "UPDATE pages SET fetched_at = ?1 WHERE id = ?2",
            params![fetched_at.to_rfc3339(), page_id],
        )?;
        Ok(())
    }

    /// Insert a batch of issues for performance.
    /// Wraps all inserts in a single SQLite transaction for O(n) vs O(n*fsync).
    pub fn insert_issues(&self, issues: &[Issue]) -> Result<(), StorageError> {
        if issues.is_empty() {
            return Ok(());
        }
        let conn = self.conn.lock();
        let tx = conn.unchecked_transaction()?;
        let mut stmt = tx.prepare(
            "INSERT INTO findings (id, page_id, category, severity, code, title, description, element, recommendation, tenant_id)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)",
        )?;
        for issue in issues {
            stmt.execute(params![
                issue.id,
                issue.page_id,
                issue.category.as_str(),
                issue.severity.as_str(),
                issue.code,
                issue.title,
                issue.description,
                issue.element,
                issue.recommendation,
                issue.tenant_id,
            ])?;
        }
        drop(stmt);
        tx.commit()?;
        Ok(())
    }

    /// Parse a URL string with a fallback to "about:invalid".
    fn parse_url_safe(s: &str) -> Url {
        Url::parse(s).unwrap_or_else(|_| {
            Url::parse("about:invalid")
                .unwrap_or_else(|_| unreachable!("about:invalid is always valid"))
        })
    }

    /// Retrieve a single page by crawl ID and URL.
    ///
    /// Returns `None` if no page matches the given URL within the crawl.
    /// Checks the LRU cache first for recently accessed pages.
    pub fn get_page(&self, crawl_id: &str, url: &str) -> Result<Option<PageData>, StorageError> {
        {
            let mut cache = self.page_cache.lock();
            if let Some(page) = cache.get(&Self::cache_key(crawl_id, url)) {
                return Ok(Some(page.clone()));
            }
        }

        let conn = self.conn.lock();
        let result = conn.query_row(
            "SELECT id, url, final_url, status_code, title, description, canonical, word_count, load_time_ms, body_size, fetched_at, tenant_id, etag, last_modified, cwv_lcp, cwv_cls, cwv_inp, has_structured_data, schema_types, viewport_ok, has_csp, has_hsts, images_total, images_missing_alt, h1_count, heading_count, extractions
             FROM pages WHERE crawl_id = ?1 AND url = ?2",
            params![crawl_id, url],
            Self::row_to_page_data,
        );

        match result {
            Ok(page) => Ok(Some(page)),
            Err(rusqlite::Error::QueryReturnedNoRows) => Ok(None),
            Err(e) => Err(StorageError::Database(e)),
        }
    }

    /// Extract a `PageData` from a database row.
    fn row_to_page_data(row: &Row<'_>) -> Result<PageData, rusqlite::Error> {
        let url_str: String = row.get(1)?;
        let final_url_str: String = row.get(2)?;
        let canonical_str: Option<String> = row.get(6)?;
        let fetched_at_str: String = row.get(10)?;

        Ok(PageData {
            id: row.get(0)?,
            url: Self::parse_url_safe(&url_str),
            final_url: Self::parse_url_safe(&final_url_str),
            status_code: row.get(3)?,
            title: row.get(4)?,
            description: row.get(5)?,
            canonical_url: canonical_str.and_then(|s| Url::parse(&s).ok()),
            word_count: row.get::<_, Option<i64>>(7)?.map(|v| v as usize),
            load_time_ms: row.get::<_, Option<i64>>(8)?.map(|v| v as u64),
            body_size: row.get::<_, Option<i64>>(9)?.map(|v| v as usize),
            fetched_at: DateTime::parse_from_rfc3339(&fetched_at_str)
                .map(|dt| dt.with_timezone(&Utc))
                .unwrap_or_else(|_| Utc::now()),
            links: Vec::new(),
            tenant_id: row.get(11)?,
            etag: row.get(12)?,
            last_modified: row.get(13)?,
            cwv_lcp: row.get(14)?,
            cwv_cls: row.get(15)?,
            cwv_inp: row.get(16)?,
            has_structured_data: row.get::<_, Option<i64>>(17)?.map(|v| v != 0),
            schema_types: row.get(18)?,
            viewport_ok: row.get::<_, Option<i64>>(19)?.map(|v| v != 0),
            has_csp: row.get::<_, Option<i64>>(20)?.map(|v| v != 0),
            has_hsts: row.get::<_, Option<i64>>(21)?.map(|v| v != 0),
            images_total: row.get::<_, Option<i64>>(22)?.map(|v| v as usize),
            images_missing_alt: row.get::<_, Option<i64>>(23)?.map(|v| v as usize),
            h1_count: row.get::<_, Option<i64>>(24)?.map(|v| v as usize),
            heading_count: row.get::<_, Option<i64>>(25)?.map(|v| v as usize),
            extractions: row.get(26)?,
        })
    }

    /// Retrieve pages with a limit.
    ///
    /// Results are not cached because the cache type (`LruCache<String, PageData>`)
    /// cannot store `Vec<PageData>`. The query is fast with proper indexing.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use crawlkit_engine::storage::{Storage, PageData};
    /// use chrono::Utc;
    /// use url::Url;
    ///
    /// let storage = Storage::new_in_memory().unwrap();
    /// let crawl_id = storage.start_crawl("https://example.com", None).unwrap();
    ///
    /// let page = PageData {
    ///     id: "p1".to_string(),
    ///     url: Url::parse("https://example.com/").unwrap(),
    ///     final_url: Url::parse("https://example.com/").unwrap(),
    ///     status_code: 200,
    ///     title: Some("Home".to_string()),
    ///     description: None,
    ///     canonical_url: None,
    ///     word_count: Some(500),
    ///     load_time_ms: Some(150),
    ///     body_size: Some(4096),
    ///     fetched_at: Utc::now(),
    ///     links: vec![],
    ///     tenant_id: None,
    ///     etag: None,
    ///     last_modified: None,
    ///     cwv_lcp: None,
    ///     cwv_cls: None,
    ///     cwv_inp: None,
    ///     has_structured_data: None,
    ///     schema_types: None,
    ///     viewport_ok: None,
    ///     has_csp: None,
    ///     has_hsts: None,
    ///     images_total: None,
    ///     images_missing_alt: None,
    ///     h1_count: None,
    ///     heading_count: None,
    ///     extractions: None,
    /// };
    /// storage.insert_page(&crawl_id, &page).unwrap();
    ///
    /// let pages = storage.get_pages(&crawl_id, 10).unwrap();
    /// assert_eq!(pages.len(), 1);
    /// assert_eq!(pages[0].url.as_str(), "https://example.com/");
    /// ```
    pub fn get_pages(&self, crawl_id: &str, limit: usize) -> Result<Vec<PageData>, StorageError> {
        let conn = self.conn.lock();
        let mut stmt = conn.prepare(
            "SELECT id, url, final_url, status_code, title, description, canonical, word_count, load_time_ms, body_size, fetched_at, tenant_id, etag, last_modified, cwv_lcp, cwv_cls, cwv_inp, has_structured_data, schema_types, viewport_ok, has_csp, has_hsts, images_total, images_missing_alt, h1_count, heading_count, extractions
             FROM pages WHERE crawl_id = ?1 ORDER BY fetched_at ASC LIMIT ?2",
        )?;

        let pages = stmt
            .query_map(params![crawl_id, limit as i64], |row| {
                Self::row_to_page_data(row)
            })?
            .collect::<Result<Vec<_>, _>>()?;

        Ok(pages)
    }

    /// Extract an `Issue` from a database row.
    fn row_to_issue(row: &Row<'_>) -> Result<Issue, rusqlite::Error> {
        let category_str: String = row.get(2)?;
        let severity_str: String = row.get(3)?;

        Ok(Issue {
            id: row.get(0)?,
            page_id: row.get(1)?,
            category: IssueCategory::parse_category(&category_str),
            severity: Severity::parse_severity(&severity_str).unwrap_or(Severity::Info),
            code: row.get(4)?,
            title: row.get(5)?,
            description: row.get(6)?,
            element: row.get(7)?,
            recommendation: row.get(8)?,
            tenant_id: row.get(9)?,
        })
    }

    /// Build an issues query with optional tenant filter.
    fn build_issues_query(
        crawl_id: &str,
        tenant_id: Option<&str>,
        filters: &IssueFilter,
    ) -> (String, Vec<Box<dyn rusqlite::types::ToSql>>) {
        let mut query = if tenant_id.is_some() {
            String::from(
                "SELECT f.id, f.page_id, f.category, f.severity, f.code, f.title, f.description, f.element, f.recommendation, f.tenant_id
                 FROM findings f
                 JOIN pages p ON f.page_id = p.id
                 WHERE p.crawl_id = ?1 AND (f.tenant_id = ?2 OR f.tenant_id IS NULL)",
            )
        } else {
            String::from(
                "SELECT f.id, f.page_id, f.category, f.severity, f.code, f.title, f.description, f.element, f.recommendation, f.tenant_id
                 FROM findings f
                 JOIN pages p ON f.page_id = p.id
                 WHERE p.crawl_id = ?1",
            )
        };
        let mut param_values: Vec<Box<dyn rusqlite::types::ToSql>> = Vec::new();
        param_values.push(Box::new(crawl_id.to_string()));
        if let Some(tid) = tenant_id {
            param_values.push(Box::new(tid.to_string()));
        }

        if let Some(ref severity) = filters.severity {
            query.push_str(&format!(" AND f.severity = ?{}", param_values.len() + 1));
            param_values.push(Box::new(severity.as_str().to_string()));
        }
        if let Some(ref category) = filters.category {
            query.push_str(&format!(" AND f.category = ?{}", param_values.len() + 1));
            param_values.push(Box::new(category.as_str()));
        }
        if let Some(ref page_id) = filters.page_id {
            query.push_str(&format!(" AND f.page_id = ?{}", param_values.len() + 1));
            param_values.push(Box::new(page_id.clone()));
        }
        if let Some(ref code_prefix) = filters.code_prefix {
            query.push_str(&format!(" AND f.code LIKE ?{}", param_values.len() + 1));
            param_values.push(Box::new(format!("{code_prefix}%")));
        }

        query.push_str(" ORDER BY f.id ASC");
        (query, param_values)
    }

    /// Execute an issues query and return results.
    fn execute_issues_query(
        conn: &Connection,
        query: &str,
        param_values: &[Box<dyn rusqlite::types::ToSql>],
    ) -> Result<Vec<Issue>, StorageError> {
        let mut stmt = conn.prepare(query)?;
        let params_refs: Vec<&dyn rusqlite::types::ToSql> =
            param_values.iter().map(|p| p.as_ref()).collect();

        let issues = stmt
            .query_map(params_refs.as_slice(), Self::row_to_issue)?
            .collect::<Result<Vec<_>, _>>()?;

        Ok(issues)
    }

    /// Retrieve issues/finding with optional filters.
    pub fn get_issues(
        &self,
        crawl_id: &str,
        filters: &IssueFilter,
    ) -> Result<Vec<Issue>, StorageError> {
        let conn = self.conn.lock();
        let (query, param_values) = Self::build_issues_query(crawl_id, None, filters);
        Self::execute_issues_query(&conn, &query, &param_values)
    }

    /// Get pages for a specific tenant.
    ///
    /// Returns pages belonging to the given tenant, or pages with no tenant
    /// assigned (shared/global data). This ensures tenant isolation at the
    /// storage layer while still allowing access to unscoped data.
    pub fn get_pages_for_tenant(
        &self,
        crawl_id: &str,
        tenant_id: &str,
        limit: usize,
    ) -> Result<Vec<PageData>, StorageError> {
        let conn = self.conn.lock();
        let mut stmt = conn.prepare(
            "SELECT id, url, final_url, status_code, title, description, canonical, word_count, load_time_ms, body_size, fetched_at, tenant_id, etag, last_modified, cwv_lcp, cwv_cls, cwv_inp, has_structured_data, schema_types, viewport_ok, has_csp, has_hsts, images_total, images_missing_alt, h1_count, heading_count, extractions
             FROM pages WHERE crawl_id = ?1 AND (tenant_id = ?2 OR tenant_id IS NULL)
             ORDER BY fetched_at ASC LIMIT ?3",
        )?;

        let pages = stmt
            .query_map(params![crawl_id, tenant_id, limit as i64], |row| {
                Self::row_to_page_data(row)
            })?
            .collect::<Result<Vec<_>, _>>()?;

        Ok(pages)
    }

    /// Get issues for a specific tenant.
    ///
    /// Returns issues belonging to the given tenant, or issues with no tenant
    /// assigned (shared/global data). This ensures tenant isolation at the
    /// storage layer while still allowing access to unscoped data.
    pub fn get_issues_for_tenant(
        &self,
        crawl_id: &str,
        tenant_id: &str,
        filters: &IssueFilter,
    ) -> Result<Vec<Issue>, StorageError> {
        let conn = self.conn.lock();
        let (query, param_values) = Self::build_issues_query(crawl_id, Some(tenant_id), filters);
        Self::execute_issues_query(&conn, &query, &param_values)
    }

    /// Get aggregate statistics for a crawl.
    pub fn get_stats(&self, crawl_id: &str) -> Result<CrawlStats, StorageError> {
        let conn = self.conn.lock();

        let total_pages: usize = conn.query_row(
            "SELECT COALESCE(COUNT(*), 0) FROM pages WHERE crawl_id = ?1",
            params![crawl_id],
            |row| row.get::<_, i64>(0),
        )? as usize;

        let total_issues: usize = conn
            .query_row(
                "SELECT COALESCE(COUNT(*), 0) FROM findings f JOIN pages p ON f.page_id = p.id WHERE p.crawl_id = ?1",
                params![crawl_id],
                |row| row.get::<_, i64>(0),
            )?
            as usize;

        let mut issues_by_severity = std::collections::HashMap::new();
        {
            let mut stmt = conn.prepare(
                "SELECT f.severity, COUNT(*) FROM findings f JOIN pages p ON f.page_id = p.id WHERE p.crawl_id = ?1 GROUP BY f.severity",
            )?;
            let rows = stmt.query_map(params![crawl_id], |row| {
                let sev: String = row.get(0)?;
                let count: i64 = row.get(1)?;
                Ok((sev, count as usize))
            })?;
            for row in rows {
                let (sev, count) = row?;
                issues_by_severity.insert(sev, count);
            }
        }

        let mut issues_by_category = std::collections::HashMap::new();
        {
            let mut stmt = conn.prepare(
                "SELECT f.category, COUNT(*) FROM findings f JOIN pages p ON f.page_id = p.id WHERE p.crawl_id = ?1 GROUP BY f.category",
            )?;
            let rows = stmt.query_map(params![crawl_id], |row| {
                let cat: String = row.get(0)?;
                let count: i64 = row.get(1)?;
                Ok((cat, count as usize))
            })?;
            for row in rows {
                let (cat, count) = row?;
                issues_by_category.insert(cat, count);
            }
        }

        let avg_response_time_ms: Option<f64> = conn
            .query_row(
                "SELECT AVG(load_time_ms) FROM pages WHERE crawl_id = ?1 AND load_time_ms IS NOT NULL",
                params![crawl_id],
                |row| row.get::<_, Option<f64>>(0),
            )
            .ok()
            .flatten();

        let total_body_size: Option<usize> = conn
            .query_row(
                "SELECT SUM(body_size) FROM pages WHERE crawl_id = ?1 AND body_size IS NOT NULL",
                params![crawl_id],
                |row| row.get::<_, Option<i64>>(0),
            )
            .ok()
            .flatten()
            .map(|v| v as usize);

        Ok(CrawlStats {
            total_pages,
            total_issues,
            issues_by_severity,
            issues_by_category,
            avg_response_time_ms,
            total_body_size,
        })
    }

    /// Get the latest crawl ID.
    pub fn get_latest_crawl_id(&self) -> Result<Option<String>, StorageError> {
        let conn = self.conn.lock();
        let result = conn.query_row(
            "SELECT id FROM crawls ORDER BY start_time DESC LIMIT 1",
            [],
            |row| row.get::<_, String>(0),
        );

        match result {
            Ok(id) => Ok(Some(id)),
            Err(rusqlite::Error::QueryReturnedNoRows) => Ok(None),
            Err(e) => Err(StorageError::Database(e)),
        }
    }

    /// Get the most recent crawl other than `exclude_id`.
    pub fn get_previous_crawl_id(&self, exclude_id: &str) -> Result<Option<String>, StorageError> {
        let conn = self.conn.lock();
        let result = conn.query_row(
            "SELECT id FROM crawls WHERE id != ?1 ORDER BY start_time DESC LIMIT 1",
            params![exclude_id],
            |row| row.get::<_, String>(0),
        );

        match result {
            Ok(id) => Ok(Some(id)),
            Err(rusqlite::Error::QueryReturnedNoRows) => Ok(None),
            Err(e) => Err(StorageError::Database(e)),
        }
    }

    /// List all crawl IDs with their timestamps, ordered chronologically.
    ///
    /// Returns `(crawl_id, start_time_rfc3339)` tuples.
    pub fn list_crawls(&self) -> Result<Vec<(String, String)>, StorageError> {
        let conn = self.conn.lock();
        let mut stmt = conn.prepare("SELECT id, start_time FROM crawls ORDER BY start_time ASC")?;
        let rows = stmt
            .query_map([], |row| {
                Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
            })?
            .collect::<Result<Vec<_>, _>>()?;
        Ok(rows)
    }

    /// Get metadata for a single crawl (target URL, timestamps, counts).
    pub fn get_crawl_meta(
        &self,
        crawl_id: &str,
    ) -> Result<crate::storage_trait::CrawlMeta, StorageError> {
        let conn = self.conn.lock();
        conn.query_row(
            "SELECT id, target_url, start_time, end_time, pages_crawled, total_issues FROM crawls WHERE id = ?1",
            params![crawl_id],
            |row| {
                Ok(crate::storage_trait::CrawlMeta {
                    id: row.get(0)?,
                    target_url: row.get(1)?,
                    start_time: row.get(2)?,
                    end_time: row.get(3)?,
                    pages_crawled: row.get::<_, i64>(4)? as usize,
                    total_issues: row.get::<_, i64>(5)? as usize,
                })
            },
        )
        .map_err(StorageError::from)
    }

    /// Get all links for a crawl, grouped by source URL.
    ///
    /// Returns `Vec<(source_url, Vec<target_url>)>` suitable for
    /// feeding into `BacklinkAnalyzer::load_from_crawl_data`.
    pub fn get_links_for_crawl(
        &self,
        crawl_id: &str,
    ) -> Result<Vec<(String, Vec<String>)>, StorageError> {
        let conn = self.conn.lock();
        let mut stmt = conn.prepare(
            "SELECT l.source_url, l.target_url
             FROM links l
             JOIN pages p ON l.page_id = p.id
             WHERE p.crawl_id = ?1
             ORDER BY l.source_url",
        )?;

        let rows = stmt.query_map(params![crawl_id], |row| {
            Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
        })?;

        let mut links: std::collections::HashMap<String, Vec<String>> =
            std::collections::HashMap::new();
        for row in rows {
            let (source, target) = row?;
            links.entry(source).or_default().push(target);
        }

        Ok(links.into_iter().collect())
    }

    /// Get all external links for a crawl.
    pub fn get_external_links(
        &self,
        crawl_id: &str,
    ) -> Result<Vec<(String, String)>, StorageError> {
        let conn = self.conn.lock();
        let mut stmt = conn.prepare(
            "SELECT l.source_url, l.target_url
             FROM links l
             JOIN pages p ON l.page_id = p.id
             WHERE p.crawl_id = ?1 AND l.is_external = 1",
        )?;

        let rows = stmt.query_map(params![crawl_id], |row| {
            Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
        })?;

        let mut links = Vec::new();
        for row in rows {
            links.push(row?);
        }

        Ok(links)
    }

    /// Get all page URLs for a crawl.
    pub fn get_page_urls(&self, crawl_id: &str) -> Result<Vec<String>, StorageError> {
        let conn = self.conn.lock();
        let mut stmt = conn.prepare("SELECT url FROM pages WHERE crawl_id = ?1 ORDER BY url")?;

        let rows = stmt.query_map(params![crawl_id], |row| row.get::<_, String>(0))?;

        let mut urls = Vec::new();
        for row in rows {
            urls.push(row?);
        }

        Ok(urls)
    }

    /// Get the conditional request data (page_id, etag, last_modified) for a URL
    /// within a crawl. Returns `None` if the URL was not previously crawled.
    pub fn get_page_conditional(
        &self,
        crawl_id: &str,
        url: &str,
    ) -> Result<Option<(String, Option<String>, Option<String>)>, StorageError> {
        let conn = self.conn.lock();
        let result = conn.query_row(
            "SELECT id, etag, last_modified FROM pages WHERE crawl_id = ?1 AND url = ?2",
            params![crawl_id, url],
            |row| {
                Ok((
                    row.get::<_, String>(0)?,
                    row.get::<_, Option<String>>(1)?,
                    row.get::<_, Option<String>>(2)?,
                ))
            },
        );

        match result {
            Ok(row) => Ok(Some(row)),
            Err(rusqlite::Error::QueryReturnedNoRows) => Ok(None),
            Err(e) => Err(StorageError::Database(e)),
        }
    }

    /// Get the most recent ETag and Last-Modified for a URL across all crawls.
    /// Used for cross-crawl incremental support.
    pub fn get_latest_conditional(
        &self,
        url: &str,
    ) -> Result<Option<(Option<String>, Option<String>)>, StorageError> {
        let conn = self.conn.lock();
        let result = conn.query_row(
            "SELECT etag, last_modified FROM pages WHERE url = ?1 ORDER BY fetched_at DESC LIMIT 1",
            params![url],
            |row| {
                Ok((
                    row.get::<_, Option<String>>(0)?,
                    row.get::<_, Option<String>>(1)?,
                ))
            },
        );

        match result {
            Ok(row) => Ok(Some(row)),
            Err(rusqlite::Error::QueryReturnedNoRows) => Ok(None),
            Err(e) => Err(StorageError::Database(e)),
        }
    }

    /// Store CrUX metrics for a page.
    pub fn insert_crux_metrics(
        &self,
        page_id: &str,
        url: &str,
        lcp_p75: Option<f64>,
        inp_p75: Option<f64>,
        cls_p75: Option<f64>,
        fcp_p75: Option<f64>,
        ttfb_p75: Option<f64>,
    ) -> Result<(), StorageError> {
        let conn = self.conn.lock();
        conn.execute(
            "INSERT OR REPLACE INTO crux_metrics (id, page_id, url, lcp_p75, inp_p75, cls_p75, fcp_p75, ttfb_p75, fetched_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)",
            params![
                uuid::Uuid::new_v4().to_string(),
                page_id,
                url,
                lcp_p75,
                inp_p75,
                cls_p75,
                fcp_p75,
                ttfb_p75,
                chrono::Utc::now().to_rfc3339(),
            ],
        )?;
        Ok(())
    }

    /// Update the Core Web Vitals fields of an existing page.
    pub fn update_page_cwv(
        &self,
        page_id: &str,
        cwv_lcp: Option<f64>,
        cwv_cls: Option<f64>,
        cwv_inp: Option<f64>,
    ) -> Result<(), StorageError> {
        let conn = self.conn.lock();
        conn.execute(
            "UPDATE pages SET cwv_lcp = ?1, cwv_cls = ?2, cwv_inp = ?3 WHERE id = ?4",
            params![cwv_lcp, cwv_cls, cwv_inp, page_id],
        )?;
        Ok(())
    }

    /// Get CrUX metrics for a page.
    pub fn get_crux_metrics(&self, page_id: &str) -> Result<Option<CruxMetrics>, StorageError> {
        let conn = self.conn.lock();
        let result = conn.query_row(
            "SELECT url, lcp_p75, inp_p75, cls_p75, fcp_p75, ttfb_p75 FROM crux_metrics WHERE page_id = ?1",
            params![page_id],
            |row| {
                Ok(CruxMetrics {
                    url: row.get(0)?,
                    lcp_p75: row.get(1)?,
                    inp_p75: row.get(2)?,
                    cls_p75: row.get(3)?,
                    fcp_p75: row.get(4)?,
                    ttfb_p75: row.get(5)?,
                })
            },
        );

        match result {
            Ok(m) => Ok(Some(m)),
            Err(rusqlite::Error::QueryReturnedNoRows) => Ok(None),
            Err(e) => Err(StorageError::Database(e)),
        }
    }

    /// Get CrUX metrics for all pages in a crawl.
    pub fn get_crux_metrics_for_crawl(
        &self,
        crawl_id: &str,
    ) -> Result<Vec<CruxMetrics>, StorageError> {
        let conn = self.conn.lock();
        let mut stmt = conn.prepare(
            "SELECT cm.url, cm.lcp_p75, cm.inp_p75, cm.cls_p75, cm.fcp_p75, cm.ttfb_p75
             FROM crux_metrics cm
             JOIN pages p ON cm.page_id = p.id
             WHERE p.crawl_id = ?1",
        )?;

        let rows = stmt.query_map(params![crawl_id], |row| {
            Ok(CruxMetrics {
                url: row.get(0)?,
                lcp_p75: row.get(1)?,
                inp_p75: row.get(2)?,
                cls_p75: row.get(3)?,
                fcp_p75: row.get(4)?,
                ttfb_p75: row.get(5)?,
            })
        })?;

        let mut metrics = Vec::new();
        for row in rows {
            metrics.push(row?);
        }

        Ok(metrics)
    }
}

impl Storage {
    /// Create a new rank-tracking project and return its ID.
    ///
    /// Part of the rank tracker storage API; see [`crate::rank`].
    pub fn add_rank_project(
        &self,
        domain: &str,
        search_engine: &str,
        device: &str,
        locale: &str,
    ) -> Result<String, StorageError> {
        let id = uuid::Uuid::new_v4().to_string();
        let conn = self.conn.lock();
        conn.execute(
            "INSERT INTO rank_projects (id, domain, search_engine, device, locale, created_at)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            params![
                id,
                domain,
                search_engine,
                device,
                locale,
                Utc::now().to_rfc3339()
            ],
        )?;
        Ok(id)
    }

    /// Add a keyword to a rank project and return its ID.
    ///
    /// Adding the same `(project_id, keyword)` pair twice is idempotent:
    /// the existing keyword's ID is returned and no row changes.
    pub fn add_rank_keyword(
        &self,
        project_id: &str,
        keyword: &str,
        target_url: Option<&str>,
    ) -> Result<String, StorageError> {
        let conn = self.conn.lock();
        conn.execute(
        "INSERT OR IGNORE INTO rank_keywords (id, project_id, keyword, target_url, enabled, created_at)
         VALUES (?1, ?2, ?3, ?4, 1, ?5)",
        params![
            uuid::Uuid::new_v4().to_string(),
            project_id,
            keyword,
            target_url,
            Utc::now().to_rfc3339()
        ],
    )?;
        let id: String = conn.query_row(
            "SELECT id FROM rank_keywords WHERE project_id = ?1 AND keyword = ?2",
            params![project_id, keyword],
            |row| row.get(0),
        )?;
        Ok(id)
    }

    /// List all rank projects, oldest first.
    pub fn list_rank_projects(&self) -> Result<Vec<crate::rank::RankProject>, StorageError> {
        let conn = self.conn.lock();
        let mut stmt = conn.prepare(
            "SELECT id, domain, search_engine, device, locale
         FROM rank_projects ORDER BY created_at ASC",
        )?;
        let rows = stmt.query_map([], |row| {
            Ok(crate::rank::RankProject {
                id: row.get(0)?,
                domain: row.get(1)?,
                search_engine: row.get(2)?,
                device: row.get(3)?,
                locale: row.get(4)?,
            })
        })?;
        Ok(rows.collect::<Result<Vec<_>, _>>()?)
    }

    /// List keywords for a rank project, oldest first.
    pub fn list_rank_keywords(
        &self,
        project_id: &str,
    ) -> Result<Vec<crate::rank::RankKeyword>, StorageError> {
        let conn = self.conn.lock();
        let mut stmt = conn.prepare(
            "SELECT id, project_id, keyword, target_url, enabled
         FROM rank_keywords WHERE project_id = ?1 ORDER BY created_at ASC",
        )?;
        let rows = stmt.query_map(params![project_id], |row| {
            Ok(crate::rank::RankKeyword {
                id: row.get(0)?,
                project_id: row.get(1)?,
                keyword: row.get(2)?,
                target_url: row.get(3)?,
                enabled: row.get::<_, Option<i64>>(4)?.unwrap_or(1) != 0,
            })
        })?;
        Ok(rows.collect::<Result<Vec<_>, _>>()?)
    }

    /// Record an observed keyword position and stamp the keyword as checked.
    pub fn record_rank_position(
        &self,
        pos: &crate::rank::RankPosition,
    ) -> Result<(), StorageError> {
        let checked_at = pos.checked_at.to_rfc3339();
        let conn = self.conn.lock();
        conn.execute(
        "INSERT OR REPLACE INTO rank_positions (id, keyword_id, checked_at, position, url, title, source)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)",
        params![
            uuid::Uuid::new_v4().to_string(),
            pos.keyword_id,
            checked_at,
            pos.position.map(i64::from),
            pos.url,
            pos.title,
            pos.source,
        ],
    )?;
        conn.execute(
            "UPDATE rank_keywords SET last_checked_at = ?1 WHERE id = ?2",
            params![checked_at, pos.keyword_id],
        )?;
        Ok(())
    }

    /// Get position history for a keyword over the trailing `days` days,
    /// oldest first.
    pub fn get_rank_history(
        &self,
        keyword_id: &str,
        days: u32,
    ) -> Result<Vec<crate::rank::RankPosition>, StorageError> {
        let cutoff = (Utc::now() - chrono::Duration::days(i64::from(days))).to_rfc3339();
        let conn = self.conn.lock();
        let mut stmt = conn.prepare(
            "SELECT keyword_id, checked_at, position, url, title, source
         FROM rank_positions
         WHERE keyword_id = ?1 AND checked_at >= ?2
         ORDER BY checked_at ASC",
        )?;
        let rows: Vec<(
            String,
            String,
            Option<i64>,
            Option<String>,
            Option<String>,
            String,
        )> = stmt
            .query_map(params![keyword_id, cutoff], |row| {
                Ok((
                    row.get::<_, String>(0)?,
                    row.get::<_, String>(1)?,
                    row.get::<_, Option<i64>>(2)?,
                    row.get::<_, Option<String>>(3)?,
                    row.get::<_, Option<String>>(4)?,
                    row.get::<_, String>(5)?,
                ))
            })?
            .collect::<Result<Vec<_>, _>>()?;

        rows.into_iter()
            .map(|(keyword_id, checked_at, position, url, title, source)| {
                Ok(crate::rank::RankPosition {
                    keyword_id,
                    checked_at: DateTime::parse_from_rfc3339(&checked_at)
                        .map_err(|e| StorageError::InvalidTimestamp(e.to_string()))?
                        .with_timezone(&Utc),
                    position: position.map(|v| v as u16),
                    url,
                    title,
                    source,
                })
            })
            .collect()
    }

    /// Remove a keyword and its recorded positions.
    pub fn remove_rank_keyword(&self, id: &str) -> Result<(), StorageError> {
        let conn = self.conn.lock();
        conn.execute(
            "DELETE FROM rank_positions WHERE keyword_id = ?1",
            params![id],
        )?;
        conn.execute("DELETE FROM rank_keywords WHERE id = ?1", params![id])?;
        Ok(())
    }
}

/// CrUX metrics for a single page.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CruxMetrics {
    pub url: String,
    pub lcp_p75: Option<f64>,
    pub inp_p75: Option<f64>,
    pub cls_p75: Option<f64>,
    pub fcp_p75: Option<f64>,
    pub ttfb_p75: Option<f64>,
}

impl crate::storage_trait::StorageBackend for Storage {
    fn add_rank_project(
        &self,
        domain: &str,
        search_engine: &str,
        device: &str,
        locale: &str,
    ) -> Result<String, StorageError> {
        Storage::add_rank_project(self, domain, search_engine, device, locale)
    }

    fn add_rank_keyword(
        &self,
        project_id: &str,
        keyword: &str,
        target_url: Option<&str>,
    ) -> Result<String, StorageError> {
        Storage::add_rank_keyword(self, project_id, keyword, target_url)
    }

    fn list_rank_projects(&self) -> Result<Vec<crate::rank::RankProject>, StorageError> {
        Storage::list_rank_projects(self)
    }

    fn list_rank_keywords(
        &self,
        project_id: &str,
    ) -> Result<Vec<crate::rank::RankKeyword>, StorageError> {
        Storage::list_rank_keywords(self, project_id)
    }

    fn record_rank_position(&self, pos: &crate::rank::RankPosition) -> Result<(), StorageError> {
        Storage::record_rank_position(self, pos)
    }

    fn get_rank_history(
        &self,
        keyword_id: &str,
        days: u32,
    ) -> Result<Vec<crate::rank::RankPosition>, StorageError> {
        Storage::get_rank_history(self, keyword_id, days)
    }

    fn remove_rank_keyword(&self, id: &str) -> Result<(), StorageError> {
        Storage::remove_rank_keyword(self, id)
    }

    fn start_crawl(
        &self,
        seed_url: &str,
        _tenant_id: Option<&str>,
    ) -> Result<String, StorageError> {
        self.start_crawl(seed_url, None)
    }

    fn finish_crawl(
        &self,
        crawl_id: &str,
        pages: usize,
        issues: usize,
    ) -> Result<(), StorageError> {
        self.finish_crawl(crawl_id, pages, issues)
    }

    fn insert_page(&self, crawl_id: &str, page: &PageData) -> Result<(), StorageError> {
        self.insert_page(crawl_id, page)
    }

    fn insert_pages_batch(&self, crawl_id: &str, pages: &[PageData]) -> Result<(), StorageError> {
        self.insert_pages(crawl_id, pages)
    }

    fn get_page(&self, crawl_id: &str, url: &str) -> Result<Option<PageData>, StorageError> {
        self.get_page(crawl_id, url)
    }

    fn get_pages(&self, crawl_id: &str, limit: usize) -> Result<Vec<PageData>, StorageError> {
        self.get_pages(crawl_id, limit)
    }

    fn get_pages_for_tenant(
        &self,
        crawl_id: &str,
        tenant_id: &str,
        limit: usize,
    ) -> Result<Vec<PageData>, StorageError> {
        self.get_pages_for_tenant(crawl_id, tenant_id, limit)
    }

    fn insert_issue(&self, issue: &Issue) -> Result<(), StorageError> {
        self.insert_issue(issue)
    }

    fn insert_issues_batch(&self, issues: &[Issue]) -> Result<(), StorageError> {
        self.insert_issues(issues)
    }

    fn get_issues(
        &self,
        crawl_id: &str,
        filters: &IssueFilter,
    ) -> Result<Vec<Issue>, StorageError> {
        self.get_issues(crawl_id, filters)
    }

    fn get_issues_for_tenant(
        &self,
        crawl_id: &str,
        tenant_id: &str,
        filters: &IssueFilter,
    ) -> Result<Vec<Issue>, StorageError> {
        self.get_issues_for_tenant(crawl_id, tenant_id, filters)
    }

    fn get_stats(&self, crawl_id: &str) -> Result<CrawlStats, StorageError> {
        self.get_stats(crawl_id)
    }

    fn get_page_conditional(
        &self,
        crawl_id: &str,
        url: &str,
    ) -> Result<Option<(String, Option<String>, Option<String>)>, StorageError> {
        self.get_page_conditional(crawl_id, url)
    }

    fn get_latest_conditional(
        &self,
        url: &str,
    ) -> Result<Option<(Option<String>, Option<String>)>, StorageError> {
        self.get_latest_conditional(url)
    }

    fn update_page_fetched_at(
        &self,
        page_id: &str,
        fetched_at: chrono::DateTime<chrono::Utc>,
    ) -> Result<(), StorageError> {
        Storage::update_page_fetched_at(self, page_id, fetched_at)
    }

    fn update_page_cwv(
        &self,
        page_id: &str,
        cwv_lcp: Option<f64>,
        cwv_cls: Option<f64>,
        cwv_inp: Option<f64>,
    ) -> Result<(), StorageError> {
        Storage::update_page_cwv(self, page_id, cwv_lcp, cwv_cls, cwv_inp)
    }

    fn list_crawls(&self) -> Result<Vec<(String, String)>, StorageError> {
        Storage::list_crawls(self)
    }

    fn get_latest_crawl_id(&self) -> Result<Option<String>, StorageError> {
        Storage::get_latest_crawl_id(self)
    }

    fn get_previous_crawl_id(&self, exclude_id: &str) -> Result<Option<String>, StorageError> {
        Storage::get_previous_crawl_id(self, exclude_id)
    }

    fn get_page_urls(&self, crawl_id: &str) -> Result<Vec<String>, StorageError> {
        Storage::get_page_urls(self, crawl_id)
    }

    fn get_links_for_crawl(
        &self,
        crawl_id: &str,
    ) -> Result<Vec<(String, Vec<String>)>, StorageError> {
        Storage::get_links_for_crawl(self, crawl_id)
    }

    fn get_external_links(&self, crawl_id: &str) -> Result<Vec<(String, String)>, StorageError> {
        Storage::get_external_links(self, crawl_id)
    }

    fn get_crawl_meta(
        &self,
        crawl_id: &str,
    ) -> Result<crate::storage_trait::CrawlMeta, StorageError> {
        let conn = self.conn.lock();
        conn.query_row(
            "SELECT id, target_url, start_time, end_time, pages_crawled, total_issues FROM crawls WHERE id = ?1",
            params![crawl_id],
            |row| {
                Ok(crate::storage_trait::CrawlMeta {
                    id: row.get(0)?,
                    target_url: row.get(1)?,
                    start_time: row.get(2)?,
                    end_time: row.get(3)?,
                    pages_crawled: row.get::<_, i64>(4)? as usize,
                    total_issues: row.get::<_, i64>(5)? as usize,
                })
            },
        )
        .map_err(StorageError::from)
    }

    fn get_top_issues(
        &self,
        crawl_id: &str,
        limit: usize,
    ) -> Result<Vec<crate::storage_trait::TopIssue>, StorageError> {
        let conn = self.conn.lock();
        let mut stmt = conn.prepare(
            "SELECT f.severity, f.code, f.title, COUNT(DISTINCT f.page_id) as affected_pages
             FROM findings f
             JOIN pages p ON f.page_id = p.id
             WHERE p.crawl_id = ?1
             GROUP BY f.severity, f.code, f.title
             ORDER BY
               CASE f.severity WHEN 'critical' THEN 0 WHEN 'error' THEN 1 WHEN 'warning' THEN 2 ELSE 3 END,
               affected_pages DESC
             LIMIT ?2",
        )?;

        let rows = stmt
            .query_map(params![crawl_id, limit as i64], |row| {
                Ok(crate::storage_trait::TopIssue {
                    severity: row.get(0)?,
                    code: row.get(1)?,
                    title: row.get(2)?,
                    affected_pages: row.get::<_, i64>(3)? as usize,
                })
            })?
            .collect::<Result<Vec<_>, _>>()?;

        let severity_rank = |s: &str| match s {
            "critical" => 0,
            "error" => 1,
            "warning" => 2,
            _ => 3,
        };
        let mut rows = rows;
        rows.sort_by(|a, b| {
            severity_rank(&a.severity)
                .cmp(&severity_rank(&b.severity))
                .then_with(|| b.affected_pages.cmp(&a.affected_pages))
                .then_with(|| a.code.cmp(&b.code))
                .then_with(|| a.title.cmp(&b.title))
        });
        rows.truncate(limit);
        Ok(rows)
    }

    fn get_crux_metrics_for_crawl(&self, crawl_id: &str) -> Result<Vec<CruxMetrics>, StorageError> {
        Storage::get_crux_metrics_for_crawl(self, crawl_id)
    }

    fn finish(&self) -> Result<(), StorageError> {
        // No-op for SQLite; connections are dropped when Storage is dropped.
        Ok(())
    }

    fn purge_old_crawls(&self, max_age_days: u32) -> Result<usize, StorageError> {
        self.purge_old_crawls(max_age_days)
    }

    fn purge_old_crawls_for_tenant(
        &self,
        max_age_days: u32,
        tenant_id: &str,
    ) -> Result<usize, StorageError> {
        self.purge_old_crawls_for_tenant(max_age_days, tenant_id)
    }

    fn compare_crawls(
        &self,
        baseline_crawl_id: &str,
        target_crawl_id: &str,
    ) -> Result<crate::compare::CrawlDiff, StorageError> {
        let conn = self.conn();
        crate::compare::compare_same_db(&conn, baseline_crawl_id, target_crawl_id).map_err(|e| {
            StorageError::Database(rusqlite::Error::InvalidParameterName(e.to_string()))
        })
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;
    use chrono::TimeZone;

    fn test_page(id: &str, url: &str, status: u16) -> PageData {
        PageData {
            id: id.to_string(),
            url: Url::parse(url).unwrap(),
            final_url: Url::parse(url).unwrap(),
            status_code: status,
            title: Some(format!("Page {id}")),
            description: None,
            canonical_url: None,
            word_count: Some(500),
            load_time_ms: Some(200),
            body_size: Some(1024),
            fetched_at: Utc::now(),
            links: vec![],
            tenant_id: None,
            etag: None,
            last_modified: None,
            cwv_lcp: None,
            cwv_cls: None,
            cwv_inp: None,
            has_structured_data: None,
            schema_types: None,
            viewport_ok: None,
            has_csp: None,
            has_hsts: None,
            images_total: None,
            images_missing_alt: None,
            h1_count: None,
            heading_count: None,
            extractions: None,
        }
    }

    fn test_issue(id: &str, page_id: &str, category: IssueCategory, severity: Severity) -> Issue {
        Issue {
            id: id.to_string(),
            page_id: page_id.to_string(),
            category,
            severity,
            code: format!("{}001", id),
            title: format!("Issue {id}"),
            description: format!("Description for issue {id}"),
            element: None,
            recommendation: "Fix this".to_string(),
            tenant_id: None,
        }
    }

    #[test]
    fn test_schema_creation() {
        let storage = Storage::new_in_memory().unwrap();
        // Schema should already exist; verify by inserting
        let crawl_id = storage.start_crawl("https://example.com", None).unwrap();
        assert!(!crawl_id.is_empty());
    }

    #[test]
    fn test_insert_and_get_pages() {
        let storage = Storage::new_in_memory().unwrap();
        let crawl_id = storage.start_crawl("https://example.com", None).unwrap();

        let pages = vec![
            test_page("p1", "https://example.com/", 200),
            test_page("p2", "https://example.com/about", 200),
        ];
        storage.insert_pages(&crawl_id, &pages).unwrap();

        let retrieved = storage.get_pages(&crawl_id, 10).unwrap();
        assert_eq!(retrieved.len(), 2);
        assert_eq!(retrieved[0].id, "p1");
        assert_eq!(retrieved[1].id, "p2");
    }

    #[test]
    fn test_insert_and_get_issues() {
        let storage = Storage::new_in_memory().unwrap();
        let crawl_id = storage.start_crawl("https://example.com", None).unwrap();

        let page = test_page("p1", "https://example.com/", 200);
        storage.insert_page(&crawl_id, &page).unwrap();

        let issues = vec![
            test_issue("i1", "p1", IssueCategory::Seo, Severity::Error),
            test_issue("i2", "p1", IssueCategory::Images, Severity::Warning),
        ];
        storage.insert_issues(&issues).unwrap();

        // Get all
        let retrieved = storage
            .get_issues(&crawl_id, &IssueFilter::default())
            .unwrap();
        assert_eq!(retrieved.len(), 2);

        // Filter by severity
        let filter = IssueFilter {
            severity: Some(Severity::Error),
            ..Default::default()
        };
        let retrieved = storage.get_issues(&crawl_id, &filter).unwrap();
        assert_eq!(retrieved.len(), 1);
        assert_eq!(retrieved[0].code, "i1001");

        // Filter by category
        let filter = IssueFilter {
            category: Some(IssueCategory::Images),
            ..Default::default()
        };
        let retrieved = storage.get_issues(&crawl_id, &filter).unwrap();
        assert_eq!(retrieved.len(), 1);
        assert_eq!(retrieved[0].code, "i2001");
    }

    #[test]
    fn test_get_stats() {
        let storage = Storage::new_in_memory().unwrap();
        let crawl_id = storage.start_crawl("https://example.com", None).unwrap();

        let pages = vec![
            test_page("p1", "https://example.com/", 200),
            test_page("p2", "https://example.com/about", 200),
        ];
        storage.insert_pages(&crawl_id, &pages).unwrap();

        let issues = vec![
            test_issue("i1", "p1", IssueCategory::Seo, Severity::Error),
            test_issue("i2", "p1", IssueCategory::Seo, Severity::Warning),
            test_issue("i3", "p2", IssueCategory::Images, Severity::Warning),
        ];
        storage.insert_issues(&issues).unwrap();

        let stats = storage.get_stats(&crawl_id).unwrap();
        assert_eq!(stats.total_pages, 2);
        assert_eq!(stats.total_issues, 3);
        assert_eq!(stats.issues_by_severity.get("error"), Some(&1));
        assert_eq!(stats.issues_by_severity.get("warning"), Some(&2));
        assert_eq!(stats.issues_by_category.get("seo"), Some(&2));
        assert_eq!(stats.issues_by_category.get("images"), Some(&1));
    }

    #[test]
    fn test_finish_crawl() {
        let storage = Storage::new_in_memory().unwrap();
        let crawl_id = storage.start_crawl("https://example.com", None).unwrap();

        let page = test_page("p1", "https://example.com/", 200);
        storage.insert_page(&crawl_id, &page).unwrap();
        let issue = test_issue("i1", "p1", IssueCategory::Seo, Severity::Error);
        storage.insert_issue(&issue).unwrap();

        storage.finish_crawl(&crawl_id, 1, 1).unwrap();
        // Verify no panic on double finish
        storage.finish_crawl(&crawl_id, 1, 1).unwrap();
    }

    #[test]
    fn test_severity_roundtrip() {
        for sev in [
            Severity::Critical,
            Severity::Error,
            Severity::Warning,
            Severity::Info,
        ] {
            let s = sev.as_str();
            assert_eq!(Severity::parse_severity(s), Some(sev));
        }
        assert_eq!(Severity::parse_severity("invalid"), None);
    }

    #[test]
    fn test_category_roundtrip() {
        for cat in [
            IssueCategory::Http,
            IssueCategory::Seo,
            IssueCategory::Content,
            IssueCategory::Links,
            IssueCategory::Images,
            IssueCategory::Schema,
            IssueCategory::Security,
            IssueCategory::Performance,
            IssueCategory::Mobile,
            IssueCategory::Accessibility,
            IssueCategory::Social,
        ] {
            let s = cat.as_str();
            assert_eq!(IssueCategory::parse_category(&s), cat);
        }
        let custom = IssueCategory::Custom("myplugin".to_string());
        let s = custom.as_str();
        assert_eq!(IssueCategory::parse_category(&s), custom);
    }

    #[test]
    fn test_pages_limit() {
        let storage = Storage::new_in_memory().unwrap();
        let crawl_id = storage.start_crawl("https://example.com", None).unwrap();

        for i in 0..10 {
            let page = test_page(
                &format!("p{i}"),
                &format!("https://example.com/page{i}"),
                200,
            );
            storage.insert_page(&crawl_id, &page).unwrap();
        }

        let pages = storage.get_pages(&crawl_id, 3).unwrap();
        assert_eq!(pages.len(), 3);
    }

    #[test]
    fn test_issue_filter_by_page_id() {
        let storage = Storage::new_in_memory().unwrap();
        let crawl_id = storage.start_crawl("https://example.com", None).unwrap();

        let p1 = test_page("p1", "https://example.com/", 200);
        let p2 = test_page("p2", "https://example.com/about", 200);
        storage.insert_page(&crawl_id, &p1).unwrap();
        storage.insert_page(&crawl_id, &p2).unwrap();

        let issues = vec![
            test_issue("i1", "p1", IssueCategory::Seo, Severity::Error),
            test_issue("i2", "p2", IssueCategory::Seo, Severity::Error),
        ];
        storage.insert_issues(&issues).unwrap();

        let filter = IssueFilter {
            page_id: Some("p1".to_string()),
            ..Default::default()
        };
        let retrieved = storage.get_issues(&crawl_id, &filter).unwrap();
        assert_eq!(retrieved.len(), 1);
        assert_eq!(retrieved[0].page_id, "p1");
    }

    #[test]
    fn test_page_conditional_etag_and_last_modified() {
        let storage = Storage::new_in_memory().unwrap();
        let crawl_id = storage.start_crawl("https://example.com", None).unwrap();

        let mut page = test_page("p1", "https://example.com/", 200);
        page.etag = Some("\"abc123\"".to_string());
        page.last_modified = Some("Wed, 21 Oct 2024 07:28:00 GMT".to_string());
        storage.insert_page(&crawl_id, &page).unwrap();

        // Retrieve conditional data
        let result = storage
            .get_page_conditional(&crawl_id, "https://example.com/")
            .unwrap();
        assert!(result.is_some());
        let (page_id, etag, last_modified) = result.unwrap();
        assert_eq!(page_id, "p1");
        assert_eq!(etag.as_deref(), Some("\"abc123\""));
        assert_eq!(
            last_modified.as_deref(),
            Some("Wed, 21 Oct 2024 07:28:00 GMT")
        );

        // Non-existent URL returns None
        let result = storage
            .get_page_conditional(&crawl_id, "https://example.com/nonexistent")
            .unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn test_page_etag_and_last_modified_roundtrip() {
        let storage = Storage::new_in_memory().unwrap();
        let crawl_id = storage.start_crawl("https://example.com", None).unwrap();

        let mut page = test_page("p1", "https://example.com/", 200);
        page.etag = Some("\"strong-etag\"".to_string());
        page.last_modified = Some("Thu, 01 Jan 2025 00:00:00 GMT".to_string());
        storage.insert_page(&crawl_id, &page).unwrap();

        let pages = storage.get_pages(&crawl_id, 10).unwrap();
        assert_eq!(pages.len(), 1);
        assert_eq!(pages[0].etag.as_deref(), Some("\"strong-etag\""));
        assert_eq!(
            pages[0].last_modified.as_deref(),
            Some("Thu, 01 Jan 2025 00:00:00 GMT")
        );
    }

    #[test]
    fn test_get_latest_conditional_cross_crawl() {
        let storage = Storage::new_in_memory().unwrap();

        // First crawl: insert a page with ETag and Last-Modified
        let crawl_id1 = storage.start_crawl("https://example.com", None).unwrap();
        let mut page1 = test_page("p1", "https://example.com/", 200);
        page1.etag = Some("\"v1-etag\"".to_string());
        page1.last_modified = Some("Mon, 01 Jan 2024 00:00:00 GMT".to_string());
        storage.insert_page(&crawl_id1, &page1).unwrap();

        // Second crawl: insert same URL with updated ETag
        let crawl_id2 = storage.start_crawl("https://example.com", None).unwrap();
        let mut page2 = test_page("p2", "https://example.com/", 200);
        page2.etag = Some("\"v2-etag\"".to_string());
        page2.last_modified = Some("Tue, 01 Jul 2025 00:00:00 GMT".to_string());
        storage.insert_page(&crawl_id2, &page2).unwrap();

        // get_page_conditional on a NEW crawl (different crawl_id) returns None
        let crawl_id3 = storage.start_crawl("https://example.com", None).unwrap();
        let result = storage
            .get_page_conditional(&crawl_id3, "https://example.com/")
            .unwrap();
        assert!(result.is_none());

        // get_latest_conditional finds the most recent entry across all crawls
        let result = storage
            .get_latest_conditional("https://example.com/")
            .unwrap();
        let (etag, last_modified) = result.unwrap();
        assert_eq!(etag.as_deref(), Some("\"v2-etag\""));
        assert_eq!(
            last_modified.as_deref(),
            Some("Tue, 01 Jul 2025 00:00:00 GMT")
        );

        // Returns None for unknown URL
        let result = storage
            .get_latest_conditional("https://example.com/unknown")
            .unwrap();
        assert!(result.is_none());
    }

    /// Build a `PageData` with every field populated (non-None), to verify
    /// that all values survive the write/read cycle with matching types.
    fn full_page(id: &str, url: &str) -> PageData {
        PageData {
            id: id.to_string(),
            url: Url::parse(url).unwrap(),
            final_url: Url::parse("https://example.com/final").unwrap(),
            status_code: 201,
            title: Some("Full Page".to_string()),
            description: Some("A page with every field populated".to_string()),
            canonical_url: Some(Url::parse("https://example.com/canonical").unwrap()),
            word_count: Some(812),
            load_time_ms: Some(321),
            body_size: Some(98_765),
            fetched_at: Utc.timestamp_opt(1_735_689_600, 123_456_789).unwrap(),
            links: vec![],
            tenant_id: Some("tenant-a".to_string()),
            etag: Some("\"full-etag\"".to_string()),
            last_modified: Some("Wed, 01 Jan 2025 00:00:00 GMT".to_string()),
            cwv_lcp: Some(1234.5),
            cwv_cls: Some(0.025),
            cwv_inp: Some(87.5),
            has_structured_data: Some(true),
            schema_types: Some("Article,BreadcrumbList".to_string()),
            viewport_ok: Some(true),
            has_csp: Some(false),
            has_hsts: Some(true),
            images_total: Some(14),
            images_missing_alt: Some(3),
            h1_count: Some(1),
            heading_count: Some(12),
            extractions: Some(r#"[["price",["9.99","19.99"]]]"#.to_string()),
        }
    }

    #[test]
    fn test_page_data_full_roundtrip() {
        let storage = Storage::new_in_memory().unwrap();
        let crawl_id = storage.start_crawl("https://example.com", None).unwrap();

        let page = full_page("p-full", "https://example.com/full");
        storage.insert_page(&crawl_id, &page).unwrap();

        // get_pages bypasses the LRU cache, so this exercises the DB read path.
        let mut pages = storage.get_pages(&crawl_id, 10).unwrap();
        assert_eq!(pages.len(), 1);
        let got = pages.remove(0);

        assert_eq!(got.id, page.id);
        assert_eq!(got.url, page.url);
        assert_eq!(got.final_url, page.final_url);
        assert_eq!(got.status_code, page.status_code);
        assert_eq!(got.title, page.title);
        assert_eq!(got.description, page.description);
        assert_eq!(got.canonical_url, page.canonical_url);
        assert_eq!(got.word_count, page.word_count);
        assert_eq!(got.load_time_ms, page.load_time_ms);
        assert_eq!(got.body_size, page.body_size);
        assert_eq!(got.fetched_at, page.fetched_at);
        assert_eq!(got.tenant_id, page.tenant_id);
        assert_eq!(got.etag, page.etag);
        assert_eq!(got.last_modified, page.last_modified);
        assert_eq!(got.cwv_lcp, page.cwv_lcp);
        assert_eq!(got.cwv_cls, page.cwv_cls);
        assert_eq!(got.cwv_inp, page.cwv_inp);
        assert_eq!(got.has_structured_data, page.has_structured_data);
        assert_eq!(got.schema_types, page.schema_types);
        assert_eq!(got.viewport_ok, page.viewport_ok);
        assert_eq!(got.has_csp, page.has_csp);
        assert_eq!(got.has_hsts, page.has_hsts);
        assert_eq!(got.images_total, page.images_total);
        assert_eq!(got.images_missing_alt, page.images_missing_alt);
        assert_eq!(got.h1_count, page.h1_count);
        assert_eq!(got.heading_count, page.heading_count);
        assert_eq!(got.extractions, page.extractions);
    }

    #[test]
    fn test_page_data_full_roundtrip_batch_insert() {
        let storage = Storage::new_in_memory().unwrap();
        let crawl_id = storage.start_crawl("https://example.com", None).unwrap();

        let page = full_page("p-batch", "https://example.com/batch");
        storage
            .insert_pages(&crawl_id, std::slice::from_ref(&page))
            .unwrap();

        let pages = storage.get_pages(&crawl_id, 10).unwrap();
        assert_eq!(pages.len(), 1);
        let got = &pages[0];

        assert_eq!(got.has_structured_data, page.has_structured_data);
        assert_eq!(got.schema_types, page.schema_types);
        assert_eq!(got.viewport_ok, page.viewport_ok);
        assert_eq!(got.has_csp, page.has_csp);
        assert_eq!(got.has_hsts, page.has_hsts);
        assert_eq!(got.images_total, page.images_total);
        assert_eq!(got.images_missing_alt, page.images_missing_alt);
        assert_eq!(got.h1_count, page.h1_count);
        assert_eq!(got.heading_count, page.heading_count);
        assert_eq!(got.extractions, page.extractions);
    }

    // ---- Rank tracker storage tests ----

    fn test_position(
        keyword_id: &str,
        position: Option<u16>,
        minutes_ago: i64,
    ) -> crate::rank::RankPosition {
        crate::rank::RankPosition {
            keyword_id: keyword_id.to_string(),
            checked_at: Utc::now() - chrono::Duration::minutes(minutes_ago),
            position,
            url: position.map(|_| "https://example.com/page".to_string()),
            title: position.map(|_| "Example Page".to_string()),
            source: "duckduckgo".to_string(),
        }
    }

    #[test]
    fn test_rank_project_crud() {
        let storage = Storage::new_in_memory().unwrap();

        let id = storage
            .add_rank_project("example.com", "duckduckgo", "desktop", "en-US")
            .unwrap();
        assert!(!id.is_empty());

        let projects = storage.list_rank_projects().unwrap();
        assert_eq!(projects.len(), 1);
        assert_eq!(projects[0].domain, "example.com");
        assert_eq!(projects[0].search_engine, "duckduckgo");
        assert_eq!(projects[0].device, "desktop");
        assert_eq!(projects[0].locale, "en-US");
    }

    #[test]
    fn test_rank_keyword_crud() {
        let storage = Storage::new_in_memory().unwrap();
        let project_id = storage
            .add_rank_project("example.com", "gsc", "mobile", "en-US")
            .unwrap();

        let kw_id = storage
            .add_rank_keyword(&project_id, "rust seo", Some("https://example.com/tools"))
            .unwrap();
        assert!(!kw_id.is_empty());

        // Duplicate add is idempotent and returns the same ID.
        let kw_id_again = storage
            .add_rank_keyword(&project_id, "rust seo", None)
            .unwrap();
        assert_eq!(kw_id, kw_id_again);

        let keywords = storage.list_rank_keywords(&project_id).unwrap();
        assert_eq!(keywords.len(), 1);
        assert_eq!(keywords[0].keyword, "rust seo");
        assert_eq!(
            keywords[0].target_url.as_deref(),
            Some("https://example.com/tools")
        );
        assert!(keywords[0].enabled);
    }

    #[test]
    fn test_rank_position_record_and_history() {
        let storage = Storage::new_in_memory().unwrap();
        let project_id = storage
            .add_rank_project("example.com", "duckduckgo", "desktop", "en-US")
            .unwrap();
        let kw_id = storage.add_rank_keyword(&project_id, "rust", None).unwrap();

        storage
            .record_rank_position(&test_position(&kw_id, Some(5), 60 * 24 * 10))
            .unwrap();
        storage
            .record_rank_position(&test_position(&kw_id, Some(3), 60 * 24))
            .unwrap();
        storage
            .record_rank_position(&test_position(&kw_id, None, 30))
            .unwrap();

        // 5-day window excludes the 10-day-old record.
        let history = storage.get_rank_history(&kw_id, 5).unwrap();
        assert_eq!(history.len(), 2);
        assert_eq!(history[0].position, Some(3));
        assert!(history[0].url.is_some());
        // Most recent check: not ranked.
        assert_eq!(history[1].position, None);

        // Full window includes everything, oldest first.
        let full = storage.get_rank_history(&kw_id, 30).unwrap();
        assert_eq!(full.len(), 3);
        assert_eq!(full[0].position, Some(5));
        assert_eq!(full[0].source, "duckduckgo");

        // last_checked_at was stamped.
        let conn = storage.conn();
        let last: Option<String> = conn
            .query_row(
                "SELECT last_checked_at FROM rank_keywords WHERE id = ?1",
                params![kw_id],
                |row| row.get(0),
            )
            .unwrap();
        assert!(last.is_some());
    }

    #[test]
    fn test_rank_remove_keyword() {
        let storage = Storage::new_in_memory().unwrap();
        let project_id = storage
            .add_rank_project("example.com", "duckduckgo", "desktop", "en-US")
            .unwrap();
        let kw_id = storage
            .add_rank_keyword(&project_id, "seo tools", None)
            .unwrap();
        storage
            .record_rank_position(&test_position(&kw_id, Some(7), 0))
            .unwrap();

        storage.remove_rank_keyword(&kw_id).unwrap();

        assert!(storage.list_rank_keywords(&project_id).unwrap().is_empty());
        assert!(storage.get_rank_history(&kw_id, 30).unwrap().is_empty());

        // Removing again is a no-op.
        storage.remove_rank_keyword(&kw_id).unwrap();
    }

    #[test]
    fn test_query_positions_table_exists() {
        let storage = Storage::new_in_memory().unwrap();
        let conn = storage.conn();
        let today = chrono::Utc::now().format("%Y-%m-%d").to_string();
        conn.execute(
            "INSERT OR REPLACE INTO query_positions (query, date, source, clicks, impressions, position, ctr)
             VALUES (?1, ?2, 'gsc', ?3, ?4, ?5, ?6)",
            params!["test query", today, 10, 100, 4.5, 0.1],
        )
        .unwrap();
        let count: i64 = conn
            .query_row("SELECT COUNT(*) FROM query_positions", [], |row| row.get(0))
            .unwrap();
        assert_eq!(count, 1);
    }
}
